import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type SiteLanguage = "en" | "de";

interface LanguageContextType {
  language: SiteLanguage;
  setLanguage: (lang: SiteLanguage) => void;
  t: (key: string) => string;
}

const translations: Record<SiteLanguage, Record<string, string>> = {
  en: {
    // Header
    "nav.whatWeDo": "What We Do",
    "nav.howWeWork": "How We Work",
    "nav.forBusinesses": "For Businesses",
    "nav.forDevelopers": "For Developers",
    "nav.caseStudies": "Case Studies",
    "nav.pricing": "Pricing",
    "nav.getInTouch": "Get in Touch",
    // Hero
    "hero.badge": "Based in Germany",
    "hero.title": "AI that runs the front office for",
    "hero.titleHighlight": "German service businesses",
    "hero.subtitle": "We find where AI saves you time and money — phone answering, booking, admin — then build it and run it for you. No hype, just working systems. Start with a free AI audit.",
    "hero.cta": "Book a free AI audit",
    "hero.secondary": "See What We Build",
    // Trust / compliance strip
    "trust.label": "Security & compliance, built in",
    "trust.gdpr.title": "GDPR-compliant",
    "trust.gdpr.desc": "Built to EU data-protection standards (DSGVO).",
    "trust.encryption.title": "End-to-end encryption",
    "trust.encryption.desc": "Your data is encrypted in transit and at rest.",
    "trust.deployment.title": "On-premise or private cloud",
    "trust.deployment.desc": "Deploy in your own environment when you need to.",
    "trust.nda.title": "Under NDA",
    "trust.nda.desc": "Every engineer works under NDA and strict security protocols.",
    // What We Do
    "whatWeDo.label": "What We Build",
    "whatWeDo.title": "The AI front office, built for you",
    "whatWeDo.subtitle": "We build the systems that answer your calls, fill your calendar, and take the admin off your team — then we run them for you.",
    "whatWeDo.saas.title": "AI Receptionists",
    "whatWeDo.saas.desc": "An AI that answers every call 24/7 in natural German, understands the caller, captures the job, and books the appointment — so no lead is ever missed.",
    "whatWeDo.mvp.title": "Booking & Scheduling",
    "whatWeDo.mvp.desc": "Self-serve appointment booking, live calendars, and automatic reminders that cut no-shows and end the phone tag.",
    "whatWeDo.automation.title": "Automation & Copilots",
    "whatWeDo.automation.desc": "We automate the repetitive admin — intake, documents, follow-ups — and build custom copilots trained on your own business.",
    // How We Work
    "howWeWork.label": "How We Work",
    "howWeWork.title": "From audit to autopilot",
    "howWeWork.subtitle": "A low-risk path: we prove the value first, build it, then run it for you.",
    "howWeWork.step1.title": "Audit",
    "howWeWork.step1.desc": "We map where AI can save you time and money, with real ROI — a fixed-scope sprint, no commitment beyond it.",
    "howWeWork.step2.title": "Build",
    "howWeWork.step2.desc": "We build the solution to production, integrated with your existing tools — in weeks, not months.",
    "howWeWork.step3.title": "Operate",
    "howWeWork.step3.desc": "We host, monitor, and run it for you, so it keeps working while you focus on your business.",
    "howWeWork.step4.title": "Scale",
    "howWeWork.step4.desc": "We extend it as you grow — more automations, more volume, new use cases.",
    // For Businesses
    "forBusinesses.label": "For Businesses",
    "forBusinesses.title": "Adopt AI With Confidence",
    "forBusinesses.subtitle": "Whether you're exploring AI for the first time or ready to scale existing initiatives, we provide the technical depth and business understanding to make it work.",
    "forBusinesses.description": "We work with SMBs and enterprises across industries. Our approach is consultative—we start by understanding your specific challenges before proposing solutions.",
    "forBusinesses.transformation.title": "AI Transformation",
    "forBusinesses.transformation.desc": "Strategic guidance on where and how to apply AI in your organization. We help you build a realistic roadmap.",
    "forBusinesses.copilots.title": "Custom Copilots",
    "forBusinesses.copilots.desc": "AI assistants tailored to your workflows. From customer support to internal operations—purpose-built for your needs.",
    "forBusinesses.automation.title": "Process Automation",
    "forBusinesses.automation.desc": "Automate document processing, data extraction, and repetitive tasks. Free your team for higher-value work.",
    "forBusinesses.enablement.title": "Team Enablement",
    "forBusinesses.enablement.desc": "Train your team to work effectively with AI tools. Practical workshops and ongoing support.",
    // For Developers
    "forDevelopers.label": "For Developers",
    "forDevelopers.title": "Build AI Solutions With Us",
    "forDevelopers.subtitle": "We're always looking for skilled developers and engineers who want to work on challenging AI projects. Whether you're interested in contract work or ongoing collaboration, let's talk.",
    "forDevelopers.benefit1": "Collaborative projects with experienced AI engineers",
    "forDevelopers.benefit2": "Modern tech stack: Python, TypeScript, cloud-native",
    "forDevelopers.benefit3": "Fair contract terms and transparent communication",
    "forDevelopers.benefit4": "Interesting problems in GenAI, LLMs, and MLOps",
    "forDevelopers.cta": "Reach Out",
    // Pricing
    "useCases.label": "What we can build",
    "useCases.title": "Real automations, real outcomes",
    "useCases.subtitle": "A few examples of what we build for service businesses — illustrative of the outcomes, not specific client data.",
    "useCases.weBuild": "We build",
    "useCases.accounting.industry": "Accounting firm",
    "useCases.accounting.problem": "Staff manually extract data from PDF invoices into DATEV.",
    "useCases.accounting.build": "AI reads PDFs, extracts and validates invoice data, flags exceptions, and prepares DATEV imports.",
    "useCases.accounting.outcome": "Bookkeepers process far more documents with the same team.",
    "useCases.manufacturing.industry": "Manufacturing",
    "useCases.manufacturing.problem": "Purchase orders arrive by email and are typed into the ERP by hand.",
    "useCases.manufacturing.build": "AI reads emails and PDFs, drafts orders in SAP/ERP, flags unusual pricing, and writes confirmations.",
    "useCases.manufacturing.outcome": "Faster order processing, fewer data-entry errors.",
    "useCases.ecommerce.industry": "E-commerce",
    "useCases.ecommerce.problem": "Support is buried in repetitive tickets — returns, tracking, sizing.",
    "useCases.ecommerce.build": "AI resolves common tickets, drafts replies for complex ones, and updates Shopify.",
    "useCases.ecommerce.outcome": "Lower support costs, faster response times.",
    "useCases.realestate.industry": "Real estate",
    "useCases.realestate.problem": "Agents repeat the same questions and chase leads manually.",
    "useCases.realestate.build": "AI chats with visitors, qualifies buyers, books viewings, and follows up automatically.",
    "useCases.realestate.outcome": "More qualified leads without another hire.",
    "useCases.medical.industry": "Medical practice",
    "useCases.medical.problem": "Reception spends hours on appointment and prescription calls.",
    "useCases.medical.build": "An AI assistant answers common questions, books appointments, and escalates complex cases to staff.",
    "useCases.medical.outcome": "Staff focus on care, not the phone.",
    "useCases.construction.industry": "Construction",
    "useCases.construction.problem": "Site updates arrive as WhatsApp messages, PDFs, and photos.",
    "useCases.construction.build": "AI organises project docs, generates daily reports, extracts invoices, and answers questions about any project.",
    "useCases.construction.outcome": "Administrative work cut dramatically.",
    "vision.label": "Our path",
    "vision.title": "We sell expertise before we sell software",
    "vision.subtitle": "We start by solving real problems for real clients. Each project funds the next and teaches us what to build — until the patterns become products.",
    "vision.step1": "Services",
    "vision.step2": "Cash flow",
    "vision.step3": "Case studies",
    "vision.step4": "Industry expertise",
    "vision.step5": "Reusable components",
    "vision.step6": "Productized service",
    "vision.step7": "SaaS",
    "vision.whyTitle": "Why we focus on the German Mittelstand",
    "vision.why1": "Profitable SMBs with real budgets for efficiency gains.",
    "vision.why2": "Slower to digitise than large enterprises — and glad of the help.",
    "vision.why3": "Little in-house AI expertise, and a preference for reliable, long-term partners.",
    "audit.label": "Start here",
    "audit.title": "Start with a free AI audit",
    "audit.subtitle": "In one focused session we map where AI can save you time and money — then hand you a plan with real ROI. No commitment, no jargon.",
    "audit.point1": "A prioritised map of AI opportunities in your business",
    "audit.point2": "Honest feasibility and ROI for each",
    "audit.point3": "A concrete, costed roadmap",
    "audit.point4": "A recommendation you can act on — with or without us",
    "audit.cta": "Book your free audit",
    "pricing.title": "How we work with you",
    "pricing.subtitle": "Start small with an audit, scale to a full build, and let us run it for you. Clear scope, fixed prices — no blank cheques.",
    "pricing.popular": "Most Popular",
    "pricing.cta": "Book a free audit",
    "pricing.note": "Every engagement starts with a free 30-minute call to scope the right fit — at no cost.",
    "pricing.starter.name": "AI Audit",
    "pricing.starter.desc": "Find where AI saves you money — before you commit",
    "pricing.starter.price": "From €2,500",
    "pricing.starter.period": "1–2 weeks",
    "pricing.starter.feature1": "Feasibility & use-case assessment",
    "pricing.starter.feature2": "Prioritised opportunity map with ROI",
    "pricing.starter.feature3": "Concrete implementation roadmap",
    "pricing.starter.feature4": "1 stakeholder workshop",
    "pricing.starter.feature5": "Fixed scope, fixed price",
    "pricing.growth.name": "AI MVP & Build",
    "pricing.growth.desc": "A working AI system your team or customers actually use",
    "pricing.growth.price": "From €15,000",
    "pricing.growth.period": "4–8 weeks",
    "pricing.growth.feature1": "Full build to production",
    "pricing.growth.feature2": "Integration with your existing tools",
    "pricing.growth.feature3": "AI receptionist, booking or automation",
    "pricing.growth.feature4": "Team training included",
    "pricing.growth.feature5": "GDPR-ready — EU or on-premise hosting",
    "pricing.growth.feature6": "30-day post-launch support",
    "pricing.enterprise.name": "Build & Operate",
    "pricing.enterprise.desc": "We build it and run it for you — a monthly partnership",
    "pricing.enterprise.price": "Custom",
    "pricing.enterprise.period": "monthly",
    "pricing.enterprise.feature1": "Everything in AI MVP & Build",
    "pricing.enterprise.feature2": "We host, monitor & operate it",
    "pricing.enterprise.feature3": "Continuous updates & improvements",
    "pricing.enterprise.feature4": "Dedicated support & SLA",
    "pricing.enterprise.feature5": "On-premise / private-cloud option",
    "pricing.enterprise.feature6": "A fractional AI team on call",
    "pricing.enterprise.feature7": "Scales as you grow",
    // Why Us
    "whyUs.label": "Why Work With Us",
    "whyUs.title": "Built Different",
    "whyUs.subtitle": "We're a small, focused team that takes pride in delivering exceptional work.",
    "whyUs.reason1.title": "Founder-Led Execution",
    "whyUs.reason1.desc": "You work directly with the founders. No account managers, no layers. Fast decisions, clear accountability.",
    "whyUs.reason2.title": "Fast & Focused",
    "whyUs.reason2.desc": "We move quickly but deliberately. Small team, tight feedback loops, and a bias toward shipping.",
    "whyUs.reason3.title": "Real AI Expertise",
    "whyUs.reason3.desc": "We build with AI every day. Not consultants who read about it—engineers who implement it in production.",
    // FAQ
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Got questions? We've got answers.",
    "faq.q1": "How do we start working together?",
    "faq.a1": "Every engagement starts with an AI Audit — a short, fixed-scope sprint where we map where AI can save you time and money, with a clear ROI and roadmap. You only commit to a full build once you've seen the plan.",
    "faq.q2": "What does it cost?",
    "faq.a2": "An AI Audit starts at €2,500. A full build (an MVP in production) starts at €15,000 depending on integrations. For solutions we run for you, we offer a monthly Build & Operate model. You always have a fixed scope and price before we start — no blank cheques.",
    "faq.q3": "Do you just advise, or do you actually build it?",
    "faq.a3": "We build. We're a studio, not a slide-deck consultancy — we design, ship, and operate real software. Our own products (an AI phone receptionist, booking platforms) are proof of what we deliver for clients.",
    "faq.q4": "Do you run it for us, or hand it over?",
    "faq.a4": "Both are options. Many clients choose Build & Operate — we host, monitor, and maintain the solution for a monthly fee, so it keeps working without you managing it. Others take ownership; we train your team and hand over.",
    "faq.q5": "How do you handle our data and GDPR?",
    "faq.a5": "GDPR is built in. We minimise the personal data used, encrypt it in transit and at rest, and can deploy on-premise or in your private cloud when your data requires it. Every engineer works under NDA.",
    "faq.q6": "How fast can we see results?",
    "faq.a6": "Fast. An audit takes 1–2 weeks; a first working system typically goes live in 4–8 weeks. We work in short milestones so you see progress early and often.",
    // Team
    "team.label": "Our Team",
    "team.title": "Meet the Founder",
    "team.founder.role": "Founder",
    "team.subtitle": "A small, dedicated team with deep expertise in AI and a passion for building exceptional products.",
    "team.valuesTitle": "Our Values",
    "team.value1.title": "Integrity",
    "team.value1.desc": "We're honest about what AI can and can't do. No overpromising.",
    "team.value2.title": "Innovation",
    "team.value2.desc": "We stay at the cutting edge while focusing on practical applications.",
    "team.value3.title": "Partnership",
    "team.value3.desc": "We work alongside your team, not just as external vendors.",
    "team.value4.title": "Excellence",
    "team.value4.desc": "We take pride in delivering quality work that exceeds expectations.",
    // Contact
    "contact.title": "Let's Talk",
    "contact.subtitle": "Whether you're exploring AI possibilities, ready to start a project, or interested in working together—we'd like to hear from you.",
    "contact.name": "Name",
    "contact.namePlaceholder": "Your name",
    "contact.email": "Email",
    "contact.emailPlaceholder": "you@company.com",
    "contact.company": "Company",
    "contact.companyPlaceholder": "Your company (optional)",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Tell us about your project or how we can help...",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.orEmail": "Or email us at",
    "contact.responseTime": "We typically respond within one business day.",
    "contact.success.title": "Message sent!",
    "contact.success.description": "We'll get back to you within one business day.",
    "contact.error.validation": "Validation error",
    "contact.error.general": "Something went wrong",
    "contact.error.tryAgain": "Please try again or email us directly.",
    "contact.error.nameRequired": "Name is required",
    "contact.error.nameTooLong": "Name must be less than 100 characters",
    "contact.error.invalidEmail": "Invalid email address",
    "contact.error.emailTooLong": "Email must be less than 255 characters",
    "contact.error.companyTooLong": "Company must be less than 100 characters",
    "contact.error.messageRequired": "Message is required",
    "contact.error.messageTooLong": "Message must be less than 2000 characters",
    // Footer
    "footer.description": "Germany-based GenAI agency building intelligent solutions for businesses.",
    "footer.careers": "Careers — we're hiring developers →",
    // Blog
    "blog.label": "Insights",
    "blog.title": "AI Insights & Updates",
    "blog.subtitle": "Stay informed with the latest trends, best practices, and insights from our AI experts.",
    "blog.readMore": "Read more",
    "blog.viewAll": "View all articles",
    "blog.post1.title": "What Does an AI Project Actually Cost? A Guide for SMBs",
    "blog.post1.excerpt": "Budgets, timelines, and what really drives the price of an AI build — from a €5k proof of concept to a production rollout. A practical cost guide for small and mid-sized businesses.",
    "blog.post2.title": "AI and GDPR: What German SMBs Need to Know",
    "blog.post2.excerpt": "Can you use AI and stay GDPR-compliant? A plain-language guide to data protection, the EU AI Act, and how to deploy AI without putting customer data at risk.",
    "blog.post3.title": "5 AI Use Cases With Fast ROI for Small Businesses",
    "blog.post3.excerpt": "Where AI pays for itself quickest in a small or mid-sized business — from answering the phone to processing invoices. Five practical, proven starting points.",
    // Blog Page
    "blogPage.backHome": "Back to Home",
    "blogPage.searchPlaceholder": "Search articles...",
    "blogPage.allCategories": "All",
    "blogPage.noResults": "No articles found matching your criteria.",
    "blogPage.post4.title": "Building Scalable AI Infrastructure: Lessons from Production",
    "blogPage.post4.excerpt": "Key insights from deploying AI systems at scale, including architecture patterns, monitoring strategies, and cost optimization techniques.",
    "blogPage.post5.title": "RAG vs Fine-tuning: Choosing the Right Approach for Your LLM",
    "blogPage.post5.excerpt": "A technical deep-dive into retrieval-augmented generation and fine-tuning, with practical guidance on when to use each approach.",
    "blogPage.post6.title": "AI Regulation in Europe: What 2025 Holds for Businesses",
    "blogPage.post6.excerpt": "An overview of upcoming AI regulations in the EU and how businesses can prepare for compliance while continuing to innovate.",
    // Blog Post Page
    "blogPost.notFound": "Article Not Found",
    "blogPost.notFoundDesc": "The article you are looking for does not exist or has been moved.",
    "blogPost.backToBlog": "Back to Blog",
    "blogPost.readTime": "read",
    "blogPost.minRemaining": "min left",
    "blogPost.relatedPosts": "Related Articles",
    "blogPost.toc.introduction": "Introduction",
    "blogPost.toc.content": "Article",
    "blogPost.toc.author": "About the Author",
    "blogPost.toc.newsletter": "Newsletter",
    "blogPost.toc.related": "Related Posts",
    "blogPost.share": "Share",
    "blogPost.ctaTitle": "Ready to Transform Your Business with AI?",
    "blogPost.ctaDesc": "Let us help you implement AI solutions that deliver real results. Schedule a free consultation today.",
    "blogPost.ctaButton": "Get in Touch",
    "blogPost.newsletter.title": "Never Miss an Update",
    "blogPost.newsletter.desc": "Subscribe to our newsletter and get the latest AI insights delivered to your inbox.",
    "blogPost.newsletter.button": "Subscribe",
    "blogPost.post1.content": "The honest answer is: it depends — but you can size it before committing a cent. AI project cost is driven by four things: how well-defined the problem is, the quality and accessibility of your data, how deep the integration goes, and whether you need ongoing operation or a one-off build.\n\nA proof of concept — enough to prove the idea works on your data — typically starts around €5,000 and takes a few weeks. It answers one question: is this worth building for real?\n\nA production MVP — something your team or customers actually use — is a larger commitment, usually a few weeks to a couple of months, depending on how deeply it integrates with your existing tools.\n\nThe biggest hidden cost isn't the model; it's the data work and the change management. Clean, accessible data and a team ready to adopt the new workflow matter more than the algorithm.\n\nOur advice: start with a fixed-scope proof of concept, measure the result against a clear business metric, and only then decide what to scale. You should never have to sign a blank cheque for AI.",
    "blogPost.post2.content": "Yes — you can use AI and stay GDPR-compliant. But it takes deliberate choices, not wishful thinking.\n\nStart with the data. The safest AI project uses the least personal data necessary. Before anything touches a model, ask: does this use case actually need personal data, and can it be anonymised or pseudonymised first?\n\nKnow where your data goes. Many AI tools send data to servers outside the EU. For sensitive use cases, that's a problem. Options that keep you in control include EU-hosted models, private-cloud deployment, or running open models on your own infrastructure.\n\nThe EU AI Act adds a second layer on top of GDPR. It classifies AI systems by risk, with the strictest obligations for high-risk uses, and requires transparency when people interact with AI. Its obligations are phasing in through 2025 and 2026.\n\nPractical steps for an SMB: keep an inventory of where AI touches personal data, sign data processing agreements with vendors, prefer EU or on-premise deployment for anything sensitive, and document your decisions. Compliance isn't a blocker to AI — it's a design constraint you build around from day one.",
    "blogPost.post3.content": "Not every AI project pays off quickly — but some reliably do. Here are five starting points where small and mid-sized businesses tend to see a return fastest.\n\n1. Answering routine calls and enquiries. A large share of inbound calls and emails are repetitive questions. An AI assistant can handle them around the clock and pass the rest to a human, so you stop losing leads after hours.\n\n2. Document and invoice processing. Extracting data from invoices, forms, and PDFs by hand is slow and error-prone. AI turns hours of manual entry into seconds of review.\n\n3. Customer support triage. AI can draft answers from your existing knowledge base and route tickets to the right person, cutting response times without cutting quality.\n\n4. Internal knowledge search. Teams waste time hunting for information across tools. A copilot trained on your own documents answers in seconds.\n\n5. Drafting content and offers. Quotes, product descriptions, and routine correspondence can be drafted by AI and finished by a human — faster, consistent, and on-brand.\n\nThe pattern: pick a task that is high-volume, rules-light, and measurable. That's where AI pays for itself first.",
    "blogPost.post4.content": "Scaling AI systems from proof-of-concept to production is where many organizations struggle. Here are the key lessons we have learned.\n\nArchitecture matters from day one. Design for scalability early, even if you do not need it immediately.\n\nMonitoring is not optional. AI systems can fail silently. Implement comprehensive monitoring for model performance.\n\nVersion everything. Models, data, configurations - all should be versioned and reproducible.\n\nPlan for model updates. AI is not a set-it-and-forget-it technology. Build processes for continuous evaluation.\n\nCost optimization is an ongoing process. Cloud AI costs can spiral quickly. Implement usage tracking and consider model optimization.",
    "blogPost.post5.content": "Retrieval-Augmented Generation (RAG) and fine-tuning are two fundamental approaches to customizing LLMs. Choosing between them requires understanding their trade-offs.\n\nRAG works by retrieving relevant documents and providing them as context. It is ideal when your knowledge base changes frequently or when you need source attribution.\n\nFine-tuning modifies the model weights themselves. It excels at adapting the model style and handling domain-specific terminology.\n\nIn practice, many successful implementations combine both approaches.\n\nConsider RAG when: data changes frequently, you need source citations, or you want faster iteration.\n\nConsider fine-tuning when: you need consistent output format or domain-specific behavior is critical.\n\nStart with RAG for most business applications - it is faster to implement and easier to update.",
    "blogPost.post6.content": "The European Union AI Act represents the most comprehensive AI regulation globally. Here is what businesses need to know.\n\nThe regulation introduces a risk-based classification system. High-risk AI applications face the strictest requirements.\n\nTimelines are staggered. Some provisions are already in effect, while others will phase in through 2025 and 2026.\n\nDocumentation requirements are substantial. You will need to demonstrate how your AI systems were developed and monitored.\n\nTransparency obligations extend to customer-facing AI. Users must be informed when they are interacting with AI systems.\n\nPenalties for non-compliance can reach 7% of global turnover.\n\nOur recommendation: conduct an AI inventory now and develop a compliance roadmap before 2025 deadlines arrive.",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.impressum": "Impressum",
    "footer.rights": "Based in Germany.",
    "footer.newsletter.title": "Stay Updated",
    "footer.newsletter.description": "Subscribe to our newsletter for AI insights and updates.",
    "footer.newsletter.placeholder": "your@email.com",
    "footer.newsletter.invalidEmail": "Invalid email",
    "footer.newsletter.enterValid": "Please enter a valid email address.",
    "footer.newsletter.alreadySubscribed": "Already subscribed",
    "footer.newsletter.alreadyOnList": "This email is already on our mailing list.",
    "footer.newsletter.subscribed": "Subscribed!",
    "footer.newsletter.thankYou": "Thank you for subscribing to our newsletter.",
    "footer.newsletter.error": "Something went wrong",
    "footer.newsletter.tryLater": "Please try again later.",
  },
  de: {
    // Header
    "nav.whatWeDo": "Was wir tun",
    "nav.howWeWork": "Wie wir arbeiten",
    "nav.forBusinesses": "Für Unternehmen",
    "nav.forDevelopers": "Für Entwickler",
    "nav.caseStudies": "Fallstudien",
    "nav.pricing": "Preise",
    "nav.getInTouch": "Kontakt",
    // Hero
    "hero.badge": "Standort Deutschland",
    "hero.title": "KI, die Ihr Tagesgeschäft übernimmt —",
    "hero.titleHighlight": "für den Mittelstand",
    "hero.subtitle": "Wir finden, wo KI Ihnen Zeit und Geld spart — Telefon, Termine, Verwaltung — bauen es und betreiben es für Sie. Kein Hype, nur funktionierende Systeme. Starten Sie mit einem kostenlosen KI-Audit.",
    "hero.cta": "Kostenloses KI-Audit buchen",
    "hero.secondary": "Was wir bauen",
    // Trust / compliance strip
    "trust.label": "Sicherheit & Compliance von Anfang an",
    "trust.gdpr.title": "DSGVO-konform",
    "trust.gdpr.desc": "Nach EU-Datenschutzstandards entwickelt.",
    "trust.encryption.title": "Ende-zu-Ende-Verschlüsselung",
    "trust.encryption.desc": "Ihre Daten sind bei Übertragung und Speicherung verschlüsselt.",
    "trust.deployment.title": "On-Premise oder Private Cloud",
    "trust.deployment.desc": "Bei Bedarf Betrieb in Ihrer eigenen Umgebung.",
    "trust.nda.title": "Unter NDA",
    "trust.nda.desc": "Jeder Entwickler arbeitet unter NDA und strengen Sicherheitsprotokollen.",
    // What We Do
    "whatWeDo.label": "Was wir bauen",
    "whatWeDo.title": "Das KI-Front-Office, für Sie gebaut",
    "whatWeDo.subtitle": "Wir bauen die Systeme, die Ihre Anrufe annehmen, Ihren Kalender füllen und Ihrem Team die Verwaltung abnehmen — und betreiben sie für Sie.",
    "whatWeDo.saas.title": "KI-Telefonassistent",
    "whatWeDo.saas.desc": "Eine KI, die jeden Anruf rund um die Uhr auf natürlichem Deutsch annimmt, das Anliegen versteht, den Auftrag erfasst und den Termin bucht — kein Lead geht verloren.",
    "whatWeDo.mvp.title": "Terminbuchung & Kalender",
    "whatWeDo.mvp.desc": "Online-Terminbuchung, Live-Kalender und automatische Erinnerungen, die No-Shows reduzieren und das Telefon-Pingpong beenden.",
    "whatWeDo.automation.title": "Automatisierung & Copiloten",
    "whatWeDo.automation.desc": "Wir automatisieren die wiederkehrende Verwaltung — Erfassung, Dokumente, Nachfassen — und bauen Copiloten, die auf Ihr Geschäft trainiert sind.",
    // How We Work
    "howWeWork.label": "Wie wir arbeiten",
    "howWeWork.title": "Vom Audit zum Autopilot",
    "howWeWork.subtitle": "Ein risikoarmer Weg: Wir beweisen zuerst den Nutzen, bauen es, dann betreiben wir es für Sie.",
    "howWeWork.step1.title": "Audit",
    "howWeWork.step1.desc": "Wir zeigen, wo KI Ihnen Zeit und Geld spart — mit echtem ROI. Fester Umfang, keine Verpflichtung darüber hinaus.",
    "howWeWork.step2.title": "Build",
    "howWeWork.step2.desc": "Wir bauen die Lösung bis zur Produktion, integriert in Ihre bestehenden Tools — in Wochen, nicht Monaten.",
    "howWeWork.step3.title": "Betrieb",
    "howWeWork.step3.desc": "Wir hosten, überwachen und betreiben es für Sie, damit es zuverlässig läuft, während Sie sich auf Ihr Geschäft konzentrieren.",
    "howWeWork.step4.title": "Skalieren",
    "howWeWork.step4.desc": "Wir erweitern es mit Ihrem Wachstum — mehr Automatisierung, mehr Volumen, neue Anwendungsfälle.",
    // For Businesses
    "forBusinesses.label": "Für Unternehmen",
    "forBusinesses.title": "KI mit Vertrauen einführen",
    "forBusinesses.subtitle": "Ob Sie KI zum ersten Mal erkunden oder bestehende Initiativen skalieren möchten—wir bieten die technische Tiefe und das Geschäftsverständnis.",
    "forBusinesses.description": "Wir arbeiten mit KMUs und Konzernen branchenübergreifend. Unser Ansatz ist beratend—wir verstehen zuerst Ihre spezifischen Herausforderungen.",
    "forBusinesses.transformation.title": "KI-Transformation",
    "forBusinesses.transformation.desc": "Strategische Beratung, wo und wie KI in Ihrer Organisation eingesetzt werden kann.",
    "forBusinesses.copilots.title": "Individuelle Copiloten",
    "forBusinesses.copilots.desc": "KI-Assistenten für Ihre Workflows. Vom Kundensupport bis zu internen Abläufen.",
    "forBusinesses.automation.title": "Prozessautomatisierung",
    "forBusinesses.automation.desc": "Automatisieren Sie Dokumentenverarbeitung, Datenextraktion und repetitive Aufgaben.",
    "forBusinesses.enablement.title": "Team-Befähigung",
    "forBusinesses.enablement.desc": "Schulen Sie Ihr Team im effektiven Umgang mit KI-Tools. Praktische Workshops und Support.",
    // For Developers
    "forDevelopers.label": "Für Entwickler",
    "forDevelopers.title": "KI-Lösungen mit uns bauen",
    "forDevelopers.subtitle": "Wir suchen immer nach erfahrenen Entwicklern, die an herausfordernden KI-Projekten arbeiten möchten. Ob Vertragarbeit oder langfristige Zusammenarbeit—lassen Sie uns sprechen.",
    "forDevelopers.benefit1": "Kollaborative Projekte mit erfahrenen KI-Ingenieuren",
    "forDevelopers.benefit2": "Moderner Tech-Stack: Python, TypeScript, Cloud-native",
    "forDevelopers.benefit3": "Faire Vertragsbedingungen und transparente Kommunikation",
    "forDevelopers.benefit4": "Interessante Probleme in GenAI, LLMs und MLOps",
    "forDevelopers.cta": "Kontakt aufnehmen",
    // Pricing
    "useCases.label": "Was wir bauen können",
    "useCases.title": "Echte Automatisierung, echte Ergebnisse",
    "useCases.subtitle": "Einige Beispiele dafür, was wir für Dienstleister bauen — illustrativ für die Ergebnisse, keine konkreten Kundendaten.",
    "useCases.weBuild": "Wir bauen",
    "useCases.accounting.industry": "Steuerkanzlei",
    "useCases.accounting.problem": "Mitarbeiter erfassen Daten aus PDF-Rechnungen manuell in DATEV.",
    "useCases.accounting.build": "KI liest PDFs, extrahiert und validiert Rechnungsdaten, markiert Ausnahmen und bereitet DATEV-Importe vor.",
    "useCases.accounting.outcome": "Buchhalter verarbeiten weit mehr Dokumente mit demselben Team.",
    "useCases.manufacturing.industry": "Fertigung",
    "useCases.manufacturing.problem": "Bestellungen kommen per E-Mail und werden von Hand ins ERP getippt.",
    "useCases.manufacturing.build": "KI liest E-Mails und PDFs, erstellt Bestellentwürfe in SAP/ERP, markiert ungewöhnliche Preise und schreibt Bestätigungen.",
    "useCases.manufacturing.outcome": "Schnellere Auftragsabwicklung, weniger Erfassungsfehler.",
    "useCases.ecommerce.industry": "E-Commerce",
    "useCases.ecommerce.problem": "Der Support versinkt in wiederkehrenden Tickets — Retouren, Sendungsverfolgung, Größen.",
    "useCases.ecommerce.build": "KI löst Standardtickets, entwirft Antworten für komplexe Fälle und aktualisiert Shopify.",
    "useCases.ecommerce.outcome": "Geringere Supportkosten, schnellere Reaktionszeiten.",
    "useCases.realestate.industry": "Immobilien",
    "useCases.realestate.problem": "Makler beantworten immer dieselben Fragen und verfolgen Leads manuell.",
    "useCases.realestate.build": "KI chattet mit Besuchern, qualifiziert Käufer, bucht Besichtigungen und fasst automatisch nach.",
    "useCases.realestate.outcome": "Mehr qualifizierte Leads ohne zusätzliche Einstellung.",
    "useCases.medical.industry": "Arztpraxis",
    "useCases.medical.problem": "Der Empfang verbringt Stunden mit Termin- und Rezeptanrufen.",
    "useCases.medical.build": "Ein KI-Assistent beantwortet häufige Fragen, bucht Termine und leitet komplexe Fälle an das Team weiter.",
    "useCases.medical.outcome": "Das Team konzentriert sich auf die Versorgung, nicht aufs Telefon.",
    "useCases.construction.industry": "Bauunternehmen",
    "useCases.construction.problem": "Baustellen-Updates kommen als WhatsApp-Nachrichten, PDFs und Fotos.",
    "useCases.construction.build": "KI organisiert Projektunterlagen, erstellt Tagesberichte, extrahiert Rechnungen und beantwortet Fragen zu jedem Projekt.",
    "useCases.construction.outcome": "Verwaltungsaufwand drastisch reduziert.",
    "vision.label": "Unser Weg",
    "vision.title": "Wir verkaufen Expertise, bevor wir Software verkaufen",
    "vision.subtitle": "Wir lösen zuerst echte Probleme für echte Kunden. Jedes Projekt finanziert das nächste und zeigt uns, was wir bauen sollten — bis aus den Mustern Produkte werden.",
    "vision.step1": "Dienstleistungen",
    "vision.step2": "Cashflow",
    "vision.step3": "Fallstudien",
    "vision.step4": "Branchenexpertise",
    "vision.step5": "Wiederverwendbare Komponenten",
    "vision.step6": "Produktisierte Leistung",
    "vision.step7": "SaaS",
    "vision.whyTitle": "Warum wir uns auf den deutschen Mittelstand konzentrieren",
    "vision.why1": "Profitable KMU mit echtem Budget für Effizienzgewinne.",
    "vision.why2": "Digitalisieren langsamer als Großkonzerne — und sind für Hilfe dankbar.",
    "vision.why3": "Wenig KI-Know-how im Haus und eine Vorliebe für verlässliche, langfristige Partner.",
    "audit.label": "Hier starten",
    "audit.title": "Starten Sie mit einem kostenlosen KI-Audit",
    "audit.subtitle": "In einer fokussierten Sitzung zeigen wir, wo KI Ihnen Zeit und Geld spart — und geben Ihnen einen Plan mit echtem ROI. Keine Verpflichtung, kein Fachjargon.",
    "audit.point1": "Eine priorisierte Karte der KI-Chancen in Ihrem Unternehmen",
    "audit.point2": "Ehrliche Machbarkeit und ROI für jede Chance",
    "audit.point3": "Ein konkreter Fahrplan mit Kosten",
    "audit.point4": "Eine Empfehlung, die Sie umsetzen können — mit oder ohne uns",
    "audit.cta": "Kostenloses Audit buchen",
    "pricing.title": "So arbeiten wir mit Ihnen",
    "pricing.subtitle": "Klein starten mit einem Audit, zum vollen Build skalieren – und wir betreiben es für Sie. Klarer Umfang, feste Preise – kein Blankoscheck.",
    "pricing.popular": "Am beliebtesten",
    "pricing.cta": "Kostenloses Audit buchen",
    "pricing.note": "Jede Zusammenarbeit beginnt mit einem kostenlosen 30-minütigen Gespräch, um den passenden Umfang zu finden.",
    "pricing.starter.name": "KI-Audit",
    "pricing.starter.desc": "Finden Sie heraus, wo KI Ihnen Geld spart – bevor Sie investieren",
    "pricing.starter.price": "Ab 2.500 €",
    "pricing.starter.period": "1–2 Wochen",
    "pricing.starter.feature1": "Machbarkeits- & Anwendungsfall-Analyse",
    "pricing.starter.feature2": "Priorisierte Potenzialkarte mit ROI",
    "pricing.starter.feature3": "Konkreter Umsetzungsfahrplan",
    "pricing.starter.feature4": "1 Stakeholder-Workshop",
    "pricing.starter.feature5": "Fester Umfang, fester Preis",
    "pricing.growth.name": "KI-MVP & Build",
    "pricing.growth.desc": "Ein funktionierendes KI-System, das Ihr Team oder Ihre Kunden wirklich nutzen",
    "pricing.growth.price": "Ab 15.000 €",
    "pricing.growth.period": "4–8 Wochen",
    "pricing.growth.feature1": "Vollständiger Build bis zur Produktion",
    "pricing.growth.feature2": "Integration in Ihre bestehenden Tools",
    "pricing.growth.feature3": "KI-Telefonassistent, Buchung oder Automatisierung",
    "pricing.growth.feature4": "Team-Training inklusive",
    "pricing.growth.feature5": "DSGVO-konform – EU- oder On-Premise-Hosting",
    "pricing.growth.feature6": "30 Tage Support nach Launch",
    "pricing.enterprise.name": "Build & Operate",
    "pricing.enterprise.desc": "Wir bauen es und betreiben es für Sie – eine monatliche Partnerschaft",
    "pricing.enterprise.price": "Individuell",
    "pricing.enterprise.period": "monatlich",
    "pricing.enterprise.feature1": "Alles aus KI-MVP & Build",
    "pricing.enterprise.feature2": "Wir hosten, überwachen & betreiben es",
    "pricing.enterprise.feature3": "Laufende Updates & Verbesserungen",
    "pricing.enterprise.feature4": "Dedizierter Support & SLA",
    "pricing.enterprise.feature5": "On-Premise / Private-Cloud-Option",
    "pricing.enterprise.feature6": "KI-Team auf Abruf",
    "pricing.enterprise.feature7": "Skaliert mit Ihrem Wachstum",
    // Why Us
    "whyUs.label": "Warum wir",
    "whyUs.title": "Anders gebaut",
    "whyUs.subtitle": "Wir sind ein kleines, fokussiertes Team, das stolz auf außergewöhnliche Arbeit ist.",
    "whyUs.reason1.title": "Gründergeführte Umsetzung",
    "whyUs.reason1.desc": "Sie arbeiten direkt mit den Gründern. Keine Account-Manager, keine Ebenen. Schnelle Entscheidungen, klare Verantwortung.",
    "whyUs.reason2.title": "Schnell & Fokussiert",
    "whyUs.reason2.desc": "Wir bewegen uns schnell, aber überlegt. Kleines Team, enge Feedback-Schleifen, Fokus aufs Liefern.",
    "whyUs.reason3.title": "Echte KI-Expertise",
    "whyUs.reason3.desc": "Wir bauen jeden Tag mit KI. Keine Berater, die darüber lesen—Ingenieure, die es in Produktion implementieren.",
    // FAQ
    "faq.title": "Häufig gestellte Fragen",
    "faq.subtitle": "Haben Sie Fragen? Wir haben Antworten.",
    "faq.q1": "Wie beginnt die Zusammenarbeit?",
    "faq.a1": "Jede Zusammenarbeit startet mit einem KI-Audit — einem kurzen Sprint mit festem Umfang, in dem wir zeigen, wo KI Ihnen Zeit und Geld spart, inklusive ROI und Fahrplan. Erst danach entscheiden Sie über einen vollständigen Build.",
    "faq.q2": "Was kostet das?",
    "faq.a2": "Ein KI-Audit beginnt bei 2.500 €. Ein vollständiger Build (ein MVP in Produktion) beginnt bei 15.000 €, je nach Integrationen. Lösungen, die wir für Sie betreiben, bieten wir im monatlichen Build-&-Operate-Modell an. Umfang und Preis stehen immer vorher fest — kein Blankoscheck.",
    "faq.q3": "Beraten Sie nur oder bauen Sie es wirklich?",
    "faq.a3": "Wir bauen. Wir sind ein Studio, keine Slide-Beratung — wir entwerfen, liefern und betreiben echte Software. Unsere eigenen Produkte (KI-Telefonassistent, Buchungsplattformen) sind der Beweis.",
    "faq.q4": "Betreiben Sie es für uns oder übergeben Sie es?",
    "faq.a4": "Beides ist möglich. Viele Kunden wählen Build & Operate — wir hosten, überwachen und warten die Lösung für eine monatliche Gebühr. Andere übernehmen selbst; wir schulen Ihr Team und übergeben.",
    "faq.q5": "Wie handhaben Sie unsere Daten und die DSGVO?",
    "faq.a5": "DSGVO ist eingebaut. Wir minimieren personenbezogene Daten, verschlüsseln bei Übertragung und Speicherung und können bei Bedarf On-Premise oder in Ihrer Private Cloud betreiben. Jeder Entwickler arbeitet unter NDA.",
    "faq.q6": "Wie schnell sehen wir Ergebnisse?",
    "faq.a6": "Schnell. Ein Audit dauert 1–2 Wochen; ein erstes funktionierendes System geht meist in 4–8 Wochen live. Wir arbeiten in kurzen Meilensteinen.",
    // Team
    "team.label": "Unser Team",
    "team.title": "Der Gründer",
    "team.founder.role": "Gründer",
    "team.subtitle": "Ein kleines, engagiertes Team mit tiefgreifender KI-Expertise und Leidenschaft für außergewöhnliche Produkte.",
    "team.valuesTitle": "Unsere Werte",
    "team.value1.title": "Integrität",
    "team.value1.desc": "Wir sind ehrlich, was KI kann und was nicht. Kein Überversprechen.",
    "team.value2.title": "Innovation",
    "team.value2.desc": "Wir bleiben an der Spitze und fokussieren uns auf praktische Anwendungen.",
    "team.value3.title": "Partnerschaft",
    "team.value3.desc": "Wir arbeiten mit Ihrem Team zusammen, nicht nur als externe Dienstleister.",
    "team.value4.title": "Exzellenz",
    "team.value4.desc": "Wir liefern Qualitätsarbeit, die Erwartungen übertrifft.",
    // Contact
    "contact.title": "Lassen Sie uns sprechen",
    "contact.subtitle": "Ob Sie KI-Möglichkeiten erkunden, ein Projekt starten oder zusammenarbeiten möchten—wir freuen uns von Ihnen zu hören.",
    "contact.name": "Name",
    "contact.namePlaceholder": "Ihr Name",
    "contact.email": "E-Mail",
    "contact.emailPlaceholder": "sie@unternehmen.de",
    "contact.company": "Unternehmen",
    "contact.companyPlaceholder": "Ihr Unternehmen (optional)",
    "contact.message": "Nachricht",
    "contact.messagePlaceholder": "Erzählen Sie uns von Ihrem Projekt oder wie wir helfen können...",
    "contact.send": "Nachricht senden",
    "contact.sending": "Wird gesendet...",
    "contact.orEmail": "Oder mailen Sie uns an",
    "contact.responseTime": "Wir antworten in der Regel innerhalb eines Werktages.",
    "contact.success.title": "Nachricht gesendet!",
    "contact.success.description": "Wir melden uns innerhalb eines Werktages bei Ihnen.",
    "contact.error.validation": "Validierungsfehler",
    "contact.error.general": "Etwas ist schiefgelaufen",
    "contact.error.tryAgain": "Bitte versuchen Sie es erneut oder mailen Sie uns direkt.",
    "contact.error.nameRequired": "Name ist erforderlich",
    "contact.error.nameTooLong": "Name muss weniger als 100 Zeichen haben",
    "contact.error.invalidEmail": "Ungültige E-Mail-Adresse",
    "contact.error.emailTooLong": "E-Mail muss weniger als 255 Zeichen haben",
    "contact.error.companyTooLong": "Unternehmen muss weniger als 100 Zeichen haben",
    "contact.error.messageRequired": "Nachricht ist erforderlich",
    "contact.error.messageTooLong": "Nachricht muss weniger als 2000 Zeichen haben",
    // Footer
    "footer.description": "Deutsche GenAI-Agentur, die intelligente Lösungen für Unternehmen entwickelt.",
    "footer.careers": "Karriere — wir stellen Entwickler ein →",
    // Blog
    "blog.label": "Einblicke",
    "blog.title": "KI-Einblicke & Updates",
    "blog.subtitle": "Bleiben Sie informiert über die neuesten Trends, Best Practices und Erkenntnisse unserer KI-Experten.",
    "blog.readMore": "Weiterlesen",
    "blog.viewAll": "Alle Artikel anzeigen",
    "blog.post1.title": "Was kostet ein KI-Projekt wirklich? Ein Leitfaden für den Mittelstand",
    "blog.post1.excerpt": "Budgets, Zeitpläne und was den Preis eines KI-Projekts wirklich bestimmt — vom 5.000-€-Proof-of-Concept bis zum Produktiv-Rollout. Ein praktischer Kostenleitfaden für KMU.",
    "blog.post2.title": "KI und DSGVO: Was der Mittelstand wissen muss",
    "blog.post2.excerpt": "Lässt sich KI DSGVO-konform einsetzen? Ein verständlicher Leitfaden zu Datenschutz, EU AI Act und wie Sie KI nutzen, ohne Kundendaten zu gefährden.",
    "blog.post3.title": "5 KI-Anwendungsfälle mit schnellem ROI für den Mittelstand",
    "blog.post3.excerpt": "Wo sich KI im Mittelstand am schnellsten rechnet — vom Telefondienst bis zur Rechnungsverarbeitung. Fünf praktische, bewährte Einstiegspunkte.",
    // Blog Page
    "blogPage.backHome": "Zurück zur Startseite",
    "blogPage.searchPlaceholder": "Artikel suchen...",
    "blogPage.allCategories": "Alle",
    "blogPage.noResults": "Keine Artikel gefunden.",
    "blogPage.post4.title": "Skalierbare KI-Infrastruktur aufbauen: Lektionen aus der Produktion",
    "blogPage.post4.excerpt": "Wichtige Erkenntnisse aus dem Deployment von KI-Systemen in großem Maßstab, einschließlich Architekturmuster und Kostenoptimierung.",
    "blogPage.post5.title": "RAG vs Fine-tuning: Die richtige Strategie für Ihr LLM",
    "blogPage.post5.excerpt": "Ein technischer Deep-Dive in Retrieval-Augmented Generation und Fine-tuning mit praktischer Anleitung.",
    "blogPage.post6.title": "KI-Regulierung in Europa: Was 2025 für Unternehmen bringt",
    "blogPage.post6.excerpt": "Ein Überblick über kommende KI-Vorschriften in der EU und wie Unternehmen sich auf Compliance vorbereiten können.",
    // Blog Post Page
    "blogPost.notFound": "Artikel nicht gefunden",
    "blogPost.notFoundDesc": "Der gesuchte Artikel existiert nicht oder wurde verschoben.",
    "blogPost.backToBlog": "Zurück zum Blog",
    "blogPost.readTime": "Lesezeit",
    "blogPost.minRemaining": "Min. übrig",
    "blogPost.relatedPosts": "Verwandte Artikel",
    "blogPost.toc.introduction": "Einleitung",
    "blogPost.toc.content": "Artikel",
    "blogPost.toc.author": "Über den Autor",
    "blogPost.toc.newsletter": "Newsletter",
    "blogPost.toc.related": "Ähnliche Beiträge",
    "blogPost.share": "Teilen",
    "blogPost.ctaTitle": "Bereit, Ihr Unternehmen mit KI zu transformieren?",
    "blogPost.ctaDesc": "Lassen Sie uns Ihnen helfen, KI-Lösungen zu implementieren, die echte Ergebnisse liefern.",
    "blogPost.ctaButton": "Kontakt aufnehmen",
    "blogPost.newsletter.title": "Kein Update verpassen",
    "blogPost.newsletter.desc": "Abonnieren Sie unseren Newsletter und erhalten Sie die neuesten KI-Insights direkt in Ihr Postfach.",
    "blogPost.newsletter.button": "Abonnieren",
    "blogPost.post1.content": "Die ehrliche Antwort lautet: Es kommt darauf an — aber Sie können es abschätzen, bevor Sie einen Cent ausgeben. Die Kosten eines KI-Projekts hängen von vier Dingen ab: wie klar das Problem definiert ist, der Qualität und Verfügbarkeit Ihrer Daten, der Integrationstiefe und ob Sie einen laufenden Betrieb oder eine einmalige Entwicklung brauchen.\n\nEin Proof of Concept — genug, um zu zeigen, dass die Idee mit Ihren Daten funktioniert — beginnt typischerweise bei etwa 5.000 € und dauert einige Wochen. Er beantwortet eine Frage: Lohnt sich die echte Umsetzung?\n\nEin Produktiv-MVP — etwas, das Ihr Team oder Ihre Kunden tatsächlich nutzen — ist eine größere Investition, meist einige Wochen bis wenige Monate, je nach Integrationstiefe in Ihre bestehenden Tools.\n\nDer größte versteckte Kostenpunkt ist nicht das Modell, sondern die Datenarbeit und das Change-Management. Saubere, zugängliche Daten und ein Team, das den neuen Ablauf annimmt, zählen mehr als der Algorithmus.\n\nUnser Rat: Beginnen Sie mit einem Proof of Concept mit festem Umfang, messen Sie das Ergebnis an einer klaren Geschäftskennzahl und entscheiden Sie erst dann, was skaliert wird. Für KI sollten Sie nie einen Blankoscheck unterschreiben müssen.",
    "blogPost.post2.content": "Ja — Sie können KI einsetzen und DSGVO-konform bleiben. Aber das erfordert bewusste Entscheidungen, kein Wunschdenken.\n\nBeginnen Sie bei den Daten. Das sicherste KI-Projekt nutzt so wenige personenbezogene Daten wie möglich. Bevor etwas ein Modell erreicht, fragen Sie: Braucht dieser Anwendungsfall wirklich personenbezogene Daten — und lassen sie sich vorher anonymisieren oder pseudonymisieren?\n\nWissen Sie, wohin Ihre Daten fließen. Viele KI-Tools senden Daten an Server außerhalb der EU. Für sensible Anwendungsfälle ist das ein Problem. Optionen, die Sie in Kontrolle halten: EU-gehostete Modelle, Private-Cloud-Betrieb oder offene Modelle auf Ihrer eigenen Infrastruktur.\n\nDer EU AI Act kommt als zweite Ebene zur DSGVO hinzu. Er klassifiziert KI-Systeme nach Risiko, mit den strengsten Pflichten für Hochrisiko-Anwendungen, und verlangt Transparenz, wenn Menschen mit KI interagieren. Seine Pflichten greifen schrittweise bis 2025 und 2026.\n\nPraktische Schritte für den Mittelstand: Führen Sie ein Verzeichnis, wo KI personenbezogene Daten berührt, schließen Sie Auftragsverarbeitungsverträge mit Anbietern, bevorzugen Sie EU- oder On-Premise-Betrieb für alles Sensible und dokumentieren Sie Ihre Entscheidungen. Compliance ist kein Hindernis für KI — sie ist eine Rahmenbedingung, die Sie von Anfang an mitdenken.",
    "blogPost.post3.content": "Nicht jedes KI-Projekt rechnet sich schnell — aber einige zuverlässig. Hier sind fünf Einstiegspunkte, an denen kleine und mittlere Unternehmen am schnellsten einen Return sehen.\n\n1. Routineanrufe und Anfragen beantworten. Ein großer Teil eingehender Anrufe und E-Mails sind wiederkehrende Fragen. Ein KI-Assistent bearbeitet sie rund um die Uhr und leitet den Rest an einen Menschen weiter — so verlieren Sie keine Anfragen mehr nach Feierabend.\n\n2. Dokumenten- und Rechnungsverarbeitung. Daten aus Rechnungen, Formularen und PDFs von Hand zu erfassen ist langsam und fehleranfällig. KI macht aus Stunden manueller Eingabe Sekunden der Prüfung.\n\n3. Triage im Kundensupport. KI entwirft Antworten aus Ihrer bestehenden Wissensbasis und leitet Tickets an die richtige Person — kürzere Antwortzeiten ohne Qualitätsverlust.\n\n4. Interne Wissenssuche. Teams verlieren Zeit bei der Suche nach Informationen über viele Tools hinweg. Ein Copilot, der auf Ihren eigenen Dokumenten trainiert ist, antwortet in Sekunden.\n\n5. Entwürfe für Inhalte und Angebote. Angebote, Produktbeschreibungen und Routinekorrespondenz kann KI entwerfen und ein Mensch fertigstellen — schneller, konsistent und markenkonform.\n\nDas Muster: Wählen Sie eine Aufgabe, die häufig vorkommt, wenige Ausnahmen hat und messbar ist. Dort rechnet sich KI zuerst.",
    "blogPost.post4.content": "Die Skalierung von KI-Systemen von der Konzeptphase zur Produktion ist eine häufige Herausforderung.\n\nArchitektur ist von Anfang an wichtig. Planen Sie für Skalierbarkeit, auch wenn Sie sie noch nicht brauchen.\n\nMonitoring ist nicht optional. KI-Systeme können still versagen.\n\nVersionieren Sie alles. Modelle, Daten, Konfigurationen sollten reproduzierbar sein.",
    "blogPost.post5.content": "RAG und Fine-tuning sind zwei grundlegende Ansätze zur Anpassung von LLMs.\n\nRAG ruft relevante Dokumente ab und stellt sie als Kontext bereit. Ideal wenn sich Ihre Wissensbasis häufig ändert.\n\nFine-tuning modifiziert die Modellgewichte selbst. Exzellent für konsistenten Output und domänenspezifisches Verhalten.\n\nIn der Praxis kombinieren viele erfolgreiche Implementierungen beide Ansätze.",
    "blogPost.post6.content": "Der EU AI Act ist die umfassendste KI-Regulierung weltweit.\n\nDie Verordnung führt ein risikobasiertes Klassifizierungssystem ein. Hochrisiko-KI-Anwendungen unterliegen den strengsten Anforderungen.\n\nZeitpläne sind gestaffelt. Einige Bestimmungen gelten bereits, andere treten bis 2026 in Kraft.\n\nDokumentationsanforderungen sind umfangreich.\n\nUnsere Empfehlung: Führen Sie jetzt eine KI-Inventur durch und entwickeln Sie eine Compliance-Roadmap.",
    "footer.legal": "Rechtliches",
    "footer.privacy": "Datenschutz",
    "footer.terms": "AGB",
    "footer.impressum": "Impressum",
    "footer.rights": "Standort Deutschland.",
    "footer.newsletter.title": "Bleiben Sie informiert",
    "footer.newsletter.description": "Abonnieren Sie unseren Newsletter für KI-Einblicke und Updates.",
    "footer.newsletter.placeholder": "ihre@email.de",
    "footer.newsletter.invalidEmail": "Ungültige E-Mail",
    "footer.newsletter.enterValid": "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    "footer.newsletter.alreadySubscribed": "Bereits abonniert",
    "footer.newsletter.alreadyOnList": "Diese E-Mail ist bereits auf unserer Liste.",
    "footer.newsletter.subscribed": "Abonniert!",
    "footer.newsletter.thankYou": "Vielen Dank für Ihr Newsletter-Abonnement.",
    "footer.newsletter.error": "Etwas ist schiefgelaufen",
    "footer.newsletter.tryLater": "Bitte versuchen Sie es später erneut.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const languageLabels: Record<SiteLanguage, { name: string; flag: string }> = {
  en: { name: "English", flag: "🇬🇧" },
  de: { name: "Deutsch", flag: "🇩🇪" },
};

const supportedLanguages: SiteLanguage[] = ["en", "de"];

const detectBrowserLanguage = (): SiteLanguage => {
  const browserLang = navigator.language.split("-")[0].toLowerCase();
  if (supportedLanguages.includes(browserLang as SiteLanguage)) {
    return browserLang as SiteLanguage;
  }
  return "en";
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<SiteLanguage>(() => {
    const saved = localStorage.getItem("site_language");
    if (saved && supportedLanguages.includes(saved as SiteLanguage)) {
      return saved as SiteLanguage;
    }
    // Auto-detect from browser if no saved preference
    return detectBrowserLanguage();
  });

  useEffect(() => {
    localStorage.setItem("site_language", language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: SiteLanguage) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
