import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type SiteLanguage = "en" | "de" | "fr" | "es" | "it";

interface LanguageContextType {
  language: SiteLanguage;
  setLanguage: (lang: SiteLanguage) => void;
  t: (key: string) => string;
}

const translations: Record<SiteLanguage, Record<string, string>> = {
  en: {
    // Header
    "nav.whatWeDo": "What We Do",
    "nav.howWeWork": "How We Work",
    "nav.forBusinesses": "For Businesses",
    "nav.forDevelopers": "For Developers",
    "nav.caseStudies": "Case Studies",
    "nav.pricing": "Pricing",
    "nav.getInTouch": "Get in Touch",
    // Hero
    "hero.badge": "Based in Germany",
    "hero.title": "AI that runs the front office for",
    "hero.titleHighlight": "German service businesses",
    "hero.subtitle": "We find where AI saves you time and money — phone answering, booking, admin — then build it and run it for you. No hype, just working systems. Start with a free AI audit.",
    "hero.cta": "Book a free AI audit",
    "hero.secondary": "See What We Build",
    // Trust / compliance strip
    "trust.label": "Security & compliance, built in",
    "trust.gdpr.title": "GDPR-compliant",
    "trust.gdpr.desc": "Built to EU data-protection standards (DSGVO).",
    "trust.encryption.title": "End-to-end encryption",
    "trust.encryption.desc": "Your data is encrypted in transit and at rest.",
    "trust.deployment.title": "On-premise or private cloud",
    "trust.deployment.desc": "Deploy in your own environment when you need to.",
    "trust.nda.title": "Under NDA",
    "trust.nda.desc": "Every engineer works under NDA and strict security protocols.",
    // What We Do
    "whatWeDo.label": "What We Do",
    "whatWeDo.title": "AI Products & Implementation",
    "whatWeDo.subtitle": "We combine deep technical expertise with a pragmatic approach to deliver AI solutions that create real business value.",
    "whatWeDo.saas.title": "GenAI SaaS Products",
    "whatWeDo.saas.desc": "We build and operate our own AI-powered software products. From concept to market, we handle the full product lifecycle.",
    "whatWeDo.mvp.title": "AI MVPs & Prototypes",
    "whatWeDo.mvp.desc": "Validate your AI ideas fast. We build functional prototypes that help you test assumptions and secure buy-in.",
    "whatWeDo.automation.title": "AI Automation",
    "whatWeDo.automation.desc": "Streamline repetitive work with intelligent automation. We integrate AI into your existing workflows and tools.",
    // How We Work
    "howWeWork.label": "How We Work",
    "howWeWork.title": "From Idea to Production",
    "howWeWork.subtitle": "Our process is designed to minimize risk and maximize learning at every stage.",
    "howWeWork.step1.title": "Idea",
    "howWeWork.step1.desc": "We start with your business challenge. Together, we identify where AI can add measurable value.",
    "howWeWork.step2.title": "MVP",
    "howWeWork.step2.desc": "Build fast, learn faster. We create working prototypes that validate assumptions in weeks, not months.",
    "howWeWork.step3.title": "Market",
    "howWeWork.step3.desc": "Test with real users. We help you gather feedback and refine the solution based on actual usage.",
    "howWeWork.step4.title": "Scale",
    "howWeWork.step4.desc": "Once validated, we help you scale reliably. Production-grade infrastructure and ongoing support.",
    // For Businesses
    "forBusinesses.label": "For Businesses",
    "forBusinesses.title": "Adopt AI With Confidence",
    "forBusinesses.subtitle": "Whether you're exploring AI for the first time or ready to scale existing initiatives, we provide the technical depth and business understanding to make it work.",
    "forBusinesses.description": "We work with SMBs and enterprises across industries. Our approach is consultative—we start by understanding your specific challenges before proposing solutions.",
    "forBusinesses.transformation.title": "AI Transformation",
    "forBusinesses.transformation.desc": "Strategic guidance on where and how to apply AI in your organization. We help you build a realistic roadmap.",
    "forBusinesses.copilots.title": "Custom Copilots",
    "forBusinesses.copilots.desc": "AI assistants tailored to your workflows. From customer support to internal operations—purpose-built for your needs.",
    "forBusinesses.automation.title": "Process Automation",
    "forBusinesses.automation.desc": "Automate document processing, data extraction, and repetitive tasks. Free your team for higher-value work.",
    "forBusinesses.enablement.title": "Team Enablement",
    "forBusinesses.enablement.desc": "Train your team to work effectively with AI tools. Practical workshops and ongoing support.",
    // For Developers
    "forDevelopers.label": "For Developers",
    "forDevelopers.title": "Build AI Solutions With Us",
    "forDevelopers.subtitle": "We're always looking for skilled developers and engineers who want to work on challenging AI projects. Whether you're interested in contract work or ongoing collaboration, let's talk.",
    "forDevelopers.benefit1": "Collaborative projects with experienced AI engineers",
    "forDevelopers.benefit2": "Modern tech stack: Python, TypeScript, cloud-native",
    "forDevelopers.benefit3": "Fair contract terms and transparent communication",
    "forDevelopers.benefit4": "Interesting problems in GenAI, LLMs, and MLOps",
    "forDevelopers.cta": "Reach Out",
    // Pricing
    "pricing.title": "How we work with you",
    "pricing.subtitle": "Start small with an audit, scale to a full build, and let us run it for you. Clear scope, fixed prices — no blank cheques.",
    "pricing.popular": "Most Popular",
    "pricing.cta": "Book a free audit",
    "pricing.note": "Every engagement starts with a free 30-minute call to scope the right fit — at no cost.",
    "pricing.starter.name": "AI Audit",
    "pricing.starter.desc": "Find where AI saves you money — before you commit",
    "pricing.starter.price": "From €2,500",
    "pricing.starter.period": "1–2 weeks",
    "pricing.starter.feature1": "Feasibility & use-case assessment",
    "pricing.starter.feature2": "Prioritised opportunity map with ROI",
    "pricing.starter.feature3": "Concrete implementation roadmap",
    "pricing.starter.feature4": "1 stakeholder workshop",
    "pricing.starter.feature5": "Fixed scope, fixed price",
    "pricing.growth.name": "AI MVP & Build",
    "pricing.growth.desc": "A working AI system your team or customers actually use",
    "pricing.growth.price": "From €15,000",
    "pricing.growth.period": "4–8 weeks",
    "pricing.growth.feature1": "Full build to production",
    "pricing.growth.feature2": "Integration with your existing tools",
    "pricing.growth.feature3": "AI receptionist, booking or automation",
    "pricing.growth.feature4": "Team training included",
    "pricing.growth.feature5": "GDPR-ready — EU or on-premise hosting",
    "pricing.growth.feature6": "30-day post-launch support",
    "pricing.enterprise.name": "Build & Operate",
    "pricing.enterprise.desc": "We build it and run it for you — a monthly partnership",
    "pricing.enterprise.price": "Custom",
    "pricing.enterprise.period": "monthly",
    "pricing.enterprise.feature1": "Everything in AI MVP & Build",
    "pricing.enterprise.feature2": "We host, monitor & operate it",
    "pricing.enterprise.feature3": "Continuous updates & improvements",
    "pricing.enterprise.feature4": "Dedicated support & SLA",
    "pricing.enterprise.feature5": "On-premise / private-cloud option",
    "pricing.enterprise.feature6": "A fractional AI team on call",
    "pricing.enterprise.feature7": "Scales as you grow",
    // Why Us
    "whyUs.label": "Why Work With Us",
    "whyUs.title": "Built Different",
    "whyUs.subtitle": "We're a small, focused team that takes pride in delivering exceptional work.",
    "whyUs.reason1.title": "Founder-Led Execution",
    "whyUs.reason1.desc": "You work directly with the founders. No account managers, no layers. Fast decisions, clear accountability.",
    "whyUs.reason2.title": "Fast & Focused",
    "whyUs.reason2.desc": "We move quickly but deliberately. Small team, tight feedback loops, and a bias toward shipping.",
    "whyUs.reason3.title": "Real AI Expertise",
    "whyUs.reason3.desc": "We build with AI every day. Not consultants who read about it—engineers who implement it in production.",
    // FAQ
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Got questions? We've got answers.",
    "faq.q1": "What types of AI solutions does xeda.ai offer?",
    "faq.a1": "We specialize in GenAI SaaS products, AI MVPs, automation solutions, AI transformation consulting, and custom copilots for businesses. Our solutions range from customer service chatbots to complex document processing systems and predictive analytics platforms.",
    "faq.q2": "How long does a typical AI project take?",
    "faq.a2": "Project timelines vary based on complexity. An AI MVP can be delivered in 4-8 weeks, while larger transformation projects typically take 3-6 months. We follow an agile approach with regular milestones so you see progress early and often.",
    "faq.q3": "Do I need technical expertise to work with xeda.ai?",
    "faq.a3": "Not at all. We handle all technical aspects of the project. Our team works closely with your business stakeholders to understand your needs and translate them into effective AI solutions. We also provide training to ensure your team can use and maintain the solutions.",
    "faq.q4": "How do you ensure data security and privacy?",
    "faq.a4": "Security is paramount in everything we build. We follow GDPR compliance, implement end-to-end encryption, and can deploy solutions on-premise or in your private cloud if required. All our developers follow strict security protocols and sign NDAs.",
    "faq.q5": "What makes xeda.ai different from other AI agencies?",
    "faq.a5": "We combine German engineering precision with cutting-edge AI expertise. Our team consists of senior developers and AI specialists who have built production systems for enterprises. We focus on practical, deployable solutions rather than experimental prototypes.",
    "faq.q6": "Do you offer ongoing support after project completion?",
    "faq.a6": "Yes, we offer flexible support and maintenance packages. This includes monitoring, updates, performance optimization, and continued development as your needs evolve. Many clients choose to work with us on a retainer basis for ongoing AI initiatives.",
    // Team
    "team.label": "Our Team",
    "team.title": "Meet the Founder",
    "team.founder.role": "Founder",
    "team.subtitle": "A small, dedicated team with deep expertise in AI and a passion for building exceptional products.",
    "team.valuesTitle": "Our Values",
    "team.alex.role": "Co-Founder & CEO",
    "team.alex.bio": "10+ years in tech leadership. Previously built AI products at leading tech companies. Passionate about practical AI solutions.",
    "team.maria.role": "Co-Founder & CTO",
    "team.maria.bio": "ML engineer with deep expertise in LLMs and production systems. Former senior engineer at top AI research labs.",
    "team.value1.title": "Integrity",
    "team.value1.desc": "We're honest about what AI can and can't do. No overpromising.",
    "team.value2.title": "Innovation",
    "team.value2.desc": "We stay at the cutting edge while focusing on practical applications.",
    "team.value3.title": "Partnership",
    "team.value3.desc": "We work alongside your team, not just as external vendors.",
    "team.value4.title": "Excellence",
    "team.value4.desc": "We take pride in delivering quality work that exceeds expectations.",
    // Contact
    "contact.title": "Let's Talk",
    "contact.subtitle": "Whether you're exploring AI possibilities, ready to start a project, or interested in working together—we'd like to hear from you.",
    "contact.name": "Name",
    "contact.namePlaceholder": "Your name",
    "contact.email": "Email",
    "contact.emailPlaceholder": "you@company.com",
    "contact.company": "Company",
    "contact.companyPlaceholder": "Your company (optional)",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Tell us about your project or how we can help...",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.orEmail": "Or email us at",
    "contact.responseTime": "We typically respond within one business day.",
    "contact.success.title": "Message sent!",
    "contact.success.description": "We'll get back to you within one business day.",
    "contact.error.validation": "Validation error",
    "contact.error.general": "Something went wrong",
    "contact.error.tryAgain": "Please try again or email us directly.",
    "contact.error.nameRequired": "Name is required",
    "contact.error.nameTooLong": "Name must be less than 100 characters",
    "contact.error.invalidEmail": "Invalid email address",
    "contact.error.emailTooLong": "Email must be less than 255 characters",
    "contact.error.companyTooLong": "Company must be less than 100 characters",
    "contact.error.messageRequired": "Message is required",
    "contact.error.messageTooLong": "Message must be less than 2000 characters",
    // Footer
    "footer.description": "Germany-based GenAI agency building intelligent solutions for businesses.",
    "footer.careers": "Careers — we're hiring developers →",
    // Blog
    "blog.label": "Insights",
    "blog.title": "AI Insights & Updates",
    "blog.subtitle": "Stay informed with the latest trends, best practices, and insights from our AI experts.",
    "blog.readMore": "Read more",
    "blog.viewAll": "View all articles",
    "blog.post1.title": "What Does an AI Project Actually Cost? A Guide for SMBs",
    "blog.post1.excerpt": "Budgets, timelines, and what really drives the price of an AI build — from a €5k proof of concept to a production rollout. A practical cost guide for small and mid-sized businesses.",
    "blog.post2.title": "AI and GDPR: What German SMBs Need to Know",
    "blog.post2.excerpt": "Can you use AI and stay GDPR-compliant? A plain-language guide to data protection, the EU AI Act, and how to deploy AI without putting customer data at risk.",
    "blog.post3.title": "5 AI Use Cases With Fast ROI for Small Businesses",
    "blog.post3.excerpt": "Where AI pays for itself quickest in a small or mid-sized business — from answering the phone to processing invoices. Five practical, proven starting points.",
    // Blog Page
    "blogPage.backHome": "Back to Home",
    "blogPage.searchPlaceholder": "Search articles...",
    "blogPage.allCategories": "All",
    "blogPage.noResults": "No articles found matching your criteria.",
    "blogPage.post4.title": "Building Scalable AI Infrastructure: Lessons from Production",
    "blogPage.post4.excerpt": "Key insights from deploying AI systems at scale, including architecture patterns, monitoring strategies, and cost optimization techniques.",
    "blogPage.post5.title": "RAG vs Fine-tuning: Choosing the Right Approach for Your LLM",
    "blogPage.post5.excerpt": "A technical deep-dive into retrieval-augmented generation and fine-tuning, with practical guidance on when to use each approach.",
    "blogPage.post6.title": "AI Regulation in Europe: What 2025 Holds for Businesses",
    "blogPage.post6.excerpt": "An overview of upcoming AI regulations in the EU and how businesses can prepare for compliance while continuing to innovate.",
    // Blog Post Page
    "blogPost.notFound": "Article Not Found",
    "blogPost.notFoundDesc": "The article you are looking for does not exist or has been moved.",
    "blogPost.backToBlog": "Back to Blog",
    "blogPost.readTime": "read",
    "blogPost.minRemaining": "min left",
    "blogPost.relatedPosts": "Related Articles",
    "blogPost.toc.introduction": "Introduction",
    "blogPost.toc.content": "Article",
    "blogPost.toc.author": "About the Author",
    "blogPost.toc.newsletter": "Newsletter",
    "blogPost.toc.related": "Related Posts",
    "blogPost.share": "Share",
    "blogPost.ctaTitle": "Ready to Transform Your Business with AI?",
    "blogPost.ctaDesc": "Let us help you implement AI solutions that deliver real results. Schedule a free consultation today.",
    "blogPost.ctaButton": "Get in Touch",
    "blogPost.newsletter.title": "Never Miss an Update",
    "blogPost.newsletter.desc": "Subscribe to our newsletter and get the latest AI insights delivered to your inbox.",
    "blogPost.newsletter.button": "Subscribe",
    "blogPost.author.alexBio": "Alex leads xeda.ai with a focus on bridging the gap between cutting-edge AI research and practical business applications. With over 10 years of experience in tech leadership, he is passionate about helping companies unlock value through intelligent automation.",
    "blogPost.author.mariaBio": "Maria brings deep technical expertise in machine learning and software architecture to xeda.ai. She specializes in designing scalable AI systems and has led successful implementations for enterprises across Europe.",
    "blogPost.post1.content": "The honest answer is: it depends — but you can size it before committing a cent. AI project cost is driven by four things: how well-defined the problem is, the quality and accessibility of your data, how deep the integration goes, and whether you need ongoing operation or a one-off build.\n\nA proof of concept — enough to prove the idea works on your data — typically starts around €5,000 and takes a few weeks. It answers one question: is this worth building for real?\n\nA production MVP — something your team or customers actually use — is a larger commitment, usually a few weeks to a couple of months, depending on how deeply it integrates with your existing tools.\n\nThe biggest hidden cost isn't the model; it's the data work and the change management. Clean, accessible data and a team ready to adopt the new workflow matter more than the algorithm.\n\nOur advice: start with a fixed-scope proof of concept, measure the result against a clear business metric, and only then decide what to scale. You should never have to sign a blank cheque for AI.",
    "blogPost.post2.content": "Yes — you can use AI and stay GDPR-compliant. But it takes deliberate choices, not wishful thinking.\n\nStart with the data. The safest AI project uses the least personal data necessary. Before anything touches a model, ask: does this use case actually need personal data, and can it be anonymised or pseudonymised first?\n\nKnow where your data goes. Many AI tools send data to servers outside the EU. For sensitive use cases, that's a problem. Options that keep you in control include EU-hosted models, private-cloud deployment, or running open models on your own infrastructure.\n\nThe EU AI Act adds a second layer on top of GDPR. It classifies AI systems by risk, with the strictest obligations for high-risk uses, and requires transparency when people interact with AI. Its obligations are phasing in through 2025 and 2026.\n\nPractical steps for an SMB: keep an inventory of where AI touches personal data, sign data processing agreements with vendors, prefer EU or on-premise deployment for anything sensitive, and document your decisions. Compliance isn't a blocker to AI — it's a design constraint you build around from day one.",
    "blogPost.post3.content": "Not every AI project pays off quickly — but some reliably do. Here are five starting points where small and mid-sized businesses tend to see a return fastest.\n\n1. Answering routine calls and enquiries. A large share of inbound calls and emails are repetitive questions. An AI assistant can handle them around the clock and pass the rest to a human, so you stop losing leads after hours.\n\n2. Document and invoice processing. Extracting data from invoices, forms, and PDFs by hand is slow and error-prone. AI turns hours of manual entry into seconds of review.\n\n3. Customer support triage. AI can draft answers from your existing knowledge base and route tickets to the right person, cutting response times without cutting quality.\n\n4. Internal knowledge search. Teams waste time hunting for information across tools. A copilot trained on your own documents answers in seconds.\n\n5. Drafting content and offers. Quotes, product descriptions, and routine correspondence can be drafted by AI and finished by a human — faster, consistent, and on-brand.\n\nThe pattern: pick a task that is high-volume, rules-light, and measurable. That's where AI pays for itself first.",
    "blogPost.post4.content": "Scaling AI systems from proof-of-concept to production is where many organizations struggle. Here are the key lessons we have learned.\n\nArchitecture matters from day one. Design for scalability early, even if you do not need it immediately.\n\nMonitoring is not optional. AI systems can fail silently. Implement comprehensive monitoring for model performance.\n\nVersion everything. Models, data, configurations - all should be versioned and reproducible.\n\nPlan for model updates. AI is not a set-it-and-forget-it technology. Build processes for continuous evaluation.\n\nCost optimization is an ongoing process. Cloud AI costs can spiral quickly. Implement usage tracking and consider model optimization.",
    "blogPost.post5.content": "Retrieval-Augmented Generation (RAG) and fine-tuning are two fundamental approaches to customizing LLMs. Choosing between them requires understanding their trade-offs.\n\nRAG works by retrieving relevant documents and providing them as context. It is ideal when your knowledge base changes frequently or when you need source attribution.\n\nFine-tuning modifies the model weights themselves. It excels at adapting the model style and handling domain-specific terminology.\n\nIn practice, many successful implementations combine both approaches.\n\nConsider RAG when: data changes frequently, you need source citations, or you want faster iteration.\n\nConsider fine-tuning when: you need consistent output format or domain-specific behavior is critical.\n\nStart with RAG for most business applications - it is faster to implement and easier to update.",
    "blogPost.post6.content": "The European Union AI Act represents the most comprehensive AI regulation globally. Here is what businesses need to know.\n\nThe regulation introduces a risk-based classification system. High-risk AI applications face the strictest requirements.\n\nTimelines are staggered. Some provisions are already in effect, while others will phase in through 2025 and 2026.\n\nDocumentation requirements are substantial. You will need to demonstrate how your AI systems were developed and monitored.\n\nTransparency obligations extend to customer-facing AI. Users must be informed when they are interacting with AI systems.\n\nPenalties for non-compliance can reach 7% of global turnover.\n\nOur recommendation: conduct an AI inventory now and develop a compliance roadmap before 2025 deadlines arrive.",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.impressum": "Impressum",
    "footer.rights": "Based in Germany.",
    "footer.newsletter.title": "Stay Updated",
    "footer.newsletter.description": "Subscribe to our newsletter for AI insights and updates.",
    "footer.newsletter.placeholder": "your@email.com",
    "footer.newsletter.invalidEmail": "Invalid email",
    "footer.newsletter.enterValid": "Please enter a valid email address.",
    "footer.newsletter.alreadySubscribed": "Already subscribed",
    "footer.newsletter.alreadyOnList": "This email is already on our mailing list.",
    "footer.newsletter.subscribed": "Subscribed!",
    "footer.newsletter.thankYou": "Thank you for subscribing to our newsletter.",
    "footer.newsletter.error": "Something went wrong",
    "footer.newsletter.tryLater": "Please try again later.",
  },
  de: {
    // Header
    "nav.whatWeDo": "Was wir tun",
    "nav.howWeWork": "Wie wir arbeiten",
    "nav.forBusinesses": "Für Unternehmen",
    "nav.forDevelopers": "Für Entwickler",
    "nav.caseStudies": "Fallstudien",
    "nav.pricing": "Preise",
    "nav.getInTouch": "Kontakt",
    // Hero
    "hero.badge": "Standort Deutschland",
    "hero.title": "KI, die Ihr Tagesgeschäft übernimmt —",
    "hero.titleHighlight": "für den Mittelstand",
    "hero.subtitle": "Wir finden, wo KI Ihnen Zeit und Geld spart — Telefon, Termine, Verwaltung — bauen es und betreiben es für Sie. Kein Hype, nur funktionierende Systeme. Starten Sie mit einem kostenlosen KI-Audit.",
    "hero.cta": "Kostenloses KI-Audit buchen",
    "hero.secondary": "Was wir bauen",
    // Trust / compliance strip
    "trust.label": "Sicherheit & Compliance von Anfang an",
    "trust.gdpr.title": "DSGVO-konform",
    "trust.gdpr.desc": "Nach EU-Datenschutzstandards entwickelt.",
    "trust.encryption.title": "Ende-zu-Ende-Verschlüsselung",
    "trust.encryption.desc": "Ihre Daten sind bei Übertragung und Speicherung verschlüsselt.",
    "trust.deployment.title": "On-Premise oder Private Cloud",
    "trust.deployment.desc": "Bei Bedarf Betrieb in Ihrer eigenen Umgebung.",
    "trust.nda.title": "Unter NDA",
    "trust.nda.desc": "Jeder Entwickler arbeitet unter NDA und strengen Sicherheitsprotokollen.",
    // What We Do
    "whatWeDo.label": "Was wir tun",
    "whatWeDo.title": "KI-Produkte & Implementierung",
    "whatWeDo.subtitle": "Wir kombinieren tiefes technisches Know-how mit einem pragmatischen Ansatz, um KI-Lösungen zu liefern, die echten Geschäftswert schaffen.",
    "whatWeDo.saas.title": "GenAI SaaS-Produkte",
    "whatWeDo.saas.desc": "Wir entwickeln und betreiben eigene KI-gestützte Softwareprodukte. Vom Konzept bis zum Markt übernehmen wir den gesamten Produktlebenszyklus.",
    "whatWeDo.mvp.title": "KI MVPs & Prototypen",
    "whatWeDo.mvp.desc": "Validieren Sie Ihre KI-Ideen schnell. Wir bauen funktionale Prototypen, die Ihnen helfen, Annahmen zu testen.",
    "whatWeDo.automation.title": "KI-Automatisierung",
    "whatWeDo.automation.desc": "Optimieren Sie repetitive Arbeit mit intelligenter Automatisierung. Wir integrieren KI in Ihre bestehenden Workflows.",
    // How We Work
    "howWeWork.label": "Wie wir arbeiten",
    "howWeWork.title": "Von der Idee zur Produktion",
    "howWeWork.subtitle": "Unser Prozess minimiert Risiken und maximiert das Lernen in jeder Phase.",
    "howWeWork.step1.title": "Idee",
    "howWeWork.step1.desc": "Wir beginnen mit Ihrer geschäftlichen Herausforderung. Gemeinsam identifizieren wir, wo KI messbaren Wert schaffen kann.",
    "howWeWork.step2.title": "MVP",
    "howWeWork.step2.desc": "Schnell bauen, schneller lernen. Wir erstellen funktionierende Prototypen, die Annahmen in Wochen validieren.",
    "howWeWork.step3.title": "Markt",
    "howWeWork.step3.desc": "Testen mit echten Nutzern. Wir helfen Ihnen, Feedback zu sammeln und die Lösung zu verfeinern.",
    "howWeWork.step4.title": "Skalieren",
    "howWeWork.step4.desc": "Nach der Validierung helfen wir Ihnen, zuverlässig zu skalieren. Produktionsreife Infrastruktur und Support.",
    // For Businesses
    "forBusinesses.label": "Für Unternehmen",
    "forBusinesses.title": "KI mit Vertrauen einführen",
    "forBusinesses.subtitle": "Ob Sie KI zum ersten Mal erkunden oder bestehende Initiativen skalieren möchten—wir bieten die technische Tiefe und das Geschäftsverständnis.",
    "forBusinesses.description": "Wir arbeiten mit KMUs und Konzernen branchenübergreifend. Unser Ansatz ist beratend—wir verstehen zuerst Ihre spezifischen Herausforderungen.",
    "forBusinesses.transformation.title": "KI-Transformation",
    "forBusinesses.transformation.desc": "Strategische Beratung, wo und wie KI in Ihrer Organisation eingesetzt werden kann.",
    "forBusinesses.copilots.title": "Individuelle Copiloten",
    "forBusinesses.copilots.desc": "KI-Assistenten für Ihre Workflows. Vom Kundensupport bis zu internen Abläufen.",
    "forBusinesses.automation.title": "Prozessautomatisierung",
    "forBusinesses.automation.desc": "Automatisieren Sie Dokumentenverarbeitung, Datenextraktion und repetitive Aufgaben.",
    "forBusinesses.enablement.title": "Team-Befähigung",
    "forBusinesses.enablement.desc": "Schulen Sie Ihr Team im effektiven Umgang mit KI-Tools. Praktische Workshops und Support.",
    // For Developers
    "forDevelopers.label": "Für Entwickler",
    "forDevelopers.title": "KI-Lösungen mit uns bauen",
    "forDevelopers.subtitle": "Wir suchen immer nach erfahrenen Entwicklern, die an herausfordernden KI-Projekten arbeiten möchten. Ob Vertragarbeit oder langfristige Zusammenarbeit—lassen Sie uns sprechen.",
    "forDevelopers.benefit1": "Kollaborative Projekte mit erfahrenen KI-Ingenieuren",
    "forDevelopers.benefit2": "Moderner Tech-Stack: Python, TypeScript, Cloud-native",
    "forDevelopers.benefit3": "Faire Vertragsbedingungen und transparente Kommunikation",
    "forDevelopers.benefit4": "Interessante Probleme in GenAI, LLMs und MLOps",
    "forDevelopers.cta": "Kontakt aufnehmen",
    // Pricing
    "pricing.title": "So arbeiten wir mit Ihnen",
    "pricing.subtitle": "Klein starten mit einem Audit, zum vollen Build skalieren – und wir betreiben es für Sie. Klarer Umfang, feste Preise – kein Blankoscheck.",
    "pricing.popular": "Am beliebtesten",
    "pricing.cta": "Kostenloses Audit buchen",
    "pricing.note": "Jede Zusammenarbeit beginnt mit einem kostenlosen 30-minütigen Gespräch, um den passenden Umfang zu finden.",
    "pricing.starter.name": "KI-Audit",
    "pricing.starter.desc": "Finden Sie heraus, wo KI Ihnen Geld spart – bevor Sie investieren",
    "pricing.starter.price": "Ab 2.500 €",
    "pricing.starter.period": "1–2 Wochen",
    "pricing.starter.feature1": "Machbarkeits- & Anwendungsfall-Analyse",
    "pricing.starter.feature2": "Priorisierte Potenzialkarte mit ROI",
    "pricing.starter.feature3": "Konkreter Umsetzungsfahrplan",
    "pricing.starter.feature4": "1 Stakeholder-Workshop",
    "pricing.starter.feature5": "Fester Umfang, fester Preis",
    "pricing.growth.name": "KI-MVP & Build",
    "pricing.growth.desc": "Ein funktionierendes KI-System, das Ihr Team oder Ihre Kunden wirklich nutzen",
    "pricing.growth.price": "Ab 15.000 €",
    "pricing.growth.period": "4–8 Wochen",
    "pricing.growth.feature1": "Vollständiger Build bis zur Produktion",
    "pricing.growth.feature2": "Integration in Ihre bestehenden Tools",
    "pricing.growth.feature3": "KI-Telefonassistent, Buchung oder Automatisierung",
    "pricing.growth.feature4": "Team-Training inklusive",
    "pricing.growth.feature5": "DSGVO-konform – EU- oder On-Premise-Hosting",
    "pricing.growth.feature6": "30 Tage Support nach Launch",
    "pricing.enterprise.name": "Build & Operate",
    "pricing.enterprise.desc": "Wir bauen es und betreiben es für Sie – eine monatliche Partnerschaft",
    "pricing.enterprise.price": "Individuell",
    "pricing.enterprise.period": "monatlich",
    "pricing.enterprise.feature1": "Alles aus KI-MVP & Build",
    "pricing.enterprise.feature2": "Wir hosten, überwachen & betreiben es",
    "pricing.enterprise.feature3": "Laufende Updates & Verbesserungen",
    "pricing.enterprise.feature4": "Dedizierter Support & SLA",
    "pricing.enterprise.feature5": "On-Premise / Private-Cloud-Option",
    "pricing.enterprise.feature6": "KI-Team auf Abruf",
    "pricing.enterprise.feature7": "Skaliert mit Ihrem Wachstum",
    // Why Us
    "whyUs.label": "Warum wir",
    "whyUs.title": "Anders gebaut",
    "whyUs.subtitle": "Wir sind ein kleines, fokussiertes Team, das stolz auf außergewöhnliche Arbeit ist.",
    "whyUs.reason1.title": "Gründergeführte Umsetzung",
    "whyUs.reason1.desc": "Sie arbeiten direkt mit den Gründern. Keine Account-Manager, keine Ebenen. Schnelle Entscheidungen, klare Verantwortung.",
    "whyUs.reason2.title": "Schnell & Fokussiert",
    "whyUs.reason2.desc": "Wir bewegen uns schnell, aber überlegt. Kleines Team, enge Feedback-Schleifen, Fokus aufs Liefern.",
    "whyUs.reason3.title": "Echte KI-Expertise",
    "whyUs.reason3.desc": "Wir bauen jeden Tag mit KI. Keine Berater, die darüber lesen—Ingenieure, die es in Produktion implementieren.",
    // FAQ
    "faq.title": "Häufig gestellte Fragen",
    "faq.subtitle": "Haben Sie Fragen? Wir haben Antworten.",
    "faq.q1": "Welche Arten von KI-Lösungen bietet xeda.ai an?",
    "faq.a1": "Wir spezialisieren uns auf GenAI SaaS-Produkte, KI-MVPs, Automatisierungslösungen, KI-Transformationsberatung und individuelle Copiloten für Unternehmen.",
    "faq.q2": "Wie lange dauert ein typisches KI-Projekt?",
    "faq.a2": "Projektzeiten variieren je nach Komplexität. Ein KI-MVP kann in 4-8 Wochen geliefert werden, während größere Transformationsprojekte 3-6 Monate dauern können.",
    "faq.q3": "Brauche ich technisches Know-how, um mit xeda.ai zu arbeiten?",
    "faq.a3": "Überhaupt nicht. Wir übernehmen alle technischen Aspekte des Projekts. Unser Team arbeitet eng mit Ihren Stakeholdern zusammen.",
    "faq.q4": "Wie stellen Sie Datensicherheit und Datenschutz sicher?",
    "faq.a4": "Sicherheit ist in allem, was wir bauen, oberstes Gebot. Wir folgen der DSGVO, implementieren End-to-End-Verschlüsselung und können Lösungen On-Premise deployen.",
    "faq.q5": "Was unterscheidet xeda.ai von anderen KI-Agenturen?",
    "faq.a5": "Wir kombinieren deutsche Ingenieurskunst mit modernster KI-Expertise. Unser Team besteht aus Senior-Entwicklern, die Produktionssysteme für Unternehmen gebaut haben.",
    "faq.q6": "Bieten Sie fortlaufenden Support nach Projektabschluss?",
    "faq.a6": "Ja, wir bieten flexible Support- und Wartungspakete. Viele Kunden arbeiten mit uns auf Retainer-Basis für laufende KI-Initiativen.",
    // Team
    "team.label": "Unser Team",
    "team.title": "Der Gründer",
    "team.founder.role": "Gründer",
    "team.subtitle": "Ein kleines, engagiertes Team mit tiefgreifender KI-Expertise und Leidenschaft für außergewöhnliche Produkte.",
    "team.valuesTitle": "Unsere Werte",
    "team.alex.role": "Mitgründer & CEO",
    "team.alex.bio": "10+ Jahre Tech-Führung. Hat zuvor KI-Produkte bei führenden Tech-Unternehmen entwickelt. Fokus auf praktische KI-Lösungen.",
    "team.maria.role": "Mitgründerin & CTO",
    "team.maria.bio": "ML-Ingenieurin mit Expertise in LLMs und Produktionssystemen. Ehemalige Senior-Ingenieurin bei führenden KI-Forschungslaboren.",
    "team.value1.title": "Integrität",
    "team.value1.desc": "Wir sind ehrlich, was KI kann und was nicht. Kein Überversprechen.",
    "team.value2.title": "Innovation",
    "team.value2.desc": "Wir bleiben an der Spitze und fokussieren uns auf praktische Anwendungen.",
    "team.value3.title": "Partnerschaft",
    "team.value3.desc": "Wir arbeiten mit Ihrem Team zusammen, nicht nur als externe Dienstleister.",
    "team.value4.title": "Exzellenz",
    "team.value4.desc": "Wir liefern Qualitätsarbeit, die Erwartungen übertrifft.",
    // Contact
    "contact.title": "Lassen Sie uns sprechen",
    "contact.subtitle": "Ob Sie KI-Möglichkeiten erkunden, ein Projekt starten oder zusammenarbeiten möchten—wir freuen uns von Ihnen zu hören.",
    "contact.name": "Name",
    "contact.namePlaceholder": "Ihr Name",
    "contact.email": "E-Mail",
    "contact.emailPlaceholder": "sie@unternehmen.de",
    "contact.company": "Unternehmen",
    "contact.companyPlaceholder": "Ihr Unternehmen (optional)",
    "contact.message": "Nachricht",
    "contact.messagePlaceholder": "Erzählen Sie uns von Ihrem Projekt oder wie wir helfen können...",
    "contact.send": "Nachricht senden",
    "contact.sending": "Wird gesendet...",
    "contact.orEmail": "Oder mailen Sie uns an",
    "contact.responseTime": "Wir antworten in der Regel innerhalb eines Werktages.",
    "contact.success.title": "Nachricht gesendet!",
    "contact.success.description": "Wir melden uns innerhalb eines Werktages bei Ihnen.",
    "contact.error.validation": "Validierungsfehler",
    "contact.error.general": "Etwas ist schiefgelaufen",
    "contact.error.tryAgain": "Bitte versuchen Sie es erneut oder mailen Sie uns direkt.",
    "contact.error.nameRequired": "Name ist erforderlich",
    "contact.error.nameTooLong": "Name muss weniger als 100 Zeichen haben",
    "contact.error.invalidEmail": "Ungültige E-Mail-Adresse",
    "contact.error.emailTooLong": "E-Mail muss weniger als 255 Zeichen haben",
    "contact.error.companyTooLong": "Unternehmen muss weniger als 100 Zeichen haben",
    "contact.error.messageRequired": "Nachricht ist erforderlich",
    "contact.error.messageTooLong": "Nachricht muss weniger als 2000 Zeichen haben",
    // Footer
    "footer.description": "Deutsche GenAI-Agentur, die intelligente Lösungen für Unternehmen entwickelt.",
    "footer.careers": "Karriere — wir stellen Entwickler ein →",
    // Blog
    "blog.label": "Einblicke",
    "blog.title": "KI-Einblicke & Updates",
    "blog.subtitle": "Bleiben Sie informiert über die neuesten Trends, Best Practices und Erkenntnisse unserer KI-Experten.",
    "blog.readMore": "Weiterlesen",
    "blog.viewAll": "Alle Artikel anzeigen",
    "blog.post1.title": "Was kostet ein KI-Projekt wirklich? Ein Leitfaden für den Mittelstand",
    "blog.post1.excerpt": "Budgets, Zeitpläne und was den Preis eines KI-Projekts wirklich bestimmt — vom 5.000-€-Proof-of-Concept bis zum Produktiv-Rollout. Ein praktischer Kostenleitfaden für KMU.",
    "blog.post2.title": "KI und DSGVO: Was der Mittelstand wissen muss",
    "blog.post2.excerpt": "Lässt sich KI DSGVO-konform einsetzen? Ein verständlicher Leitfaden zu Datenschutz, EU AI Act und wie Sie KI nutzen, ohne Kundendaten zu gefährden.",
    "blog.post3.title": "5 KI-Anwendungsfälle mit schnellem ROI für den Mittelstand",
    "blog.post3.excerpt": "Wo sich KI im Mittelstand am schnellsten rechnet — vom Telefondienst bis zur Rechnungsverarbeitung. Fünf praktische, bewährte Einstiegspunkte.",
    // Blog Page
    "blogPage.backHome": "Zurück zur Startseite",
    "blogPage.searchPlaceholder": "Artikel suchen...",
    "blogPage.allCategories": "Alle",
    "blogPage.noResults": "Keine Artikel gefunden.",
    "blogPage.post4.title": "Skalierbare KI-Infrastruktur aufbauen: Lektionen aus der Produktion",
    "blogPage.post4.excerpt": "Wichtige Erkenntnisse aus dem Deployment von KI-Systemen in großem Maßstab, einschließlich Architekturmuster und Kostenoptimierung.",
    "blogPage.post5.title": "RAG vs Fine-tuning: Die richtige Strategie für Ihr LLM",
    "blogPage.post5.excerpt": "Ein technischer Deep-Dive in Retrieval-Augmented Generation und Fine-tuning mit praktischer Anleitung.",
    "blogPage.post6.title": "KI-Regulierung in Europa: Was 2025 für Unternehmen bringt",
    "blogPage.post6.excerpt": "Ein Überblick über kommende KI-Vorschriften in der EU und wie Unternehmen sich auf Compliance vorbereiten können.",
    // Blog Post Page
    "blogPost.notFound": "Artikel nicht gefunden",
    "blogPost.notFoundDesc": "Der gesuchte Artikel existiert nicht oder wurde verschoben.",
    "blogPost.backToBlog": "Zurück zum Blog",
    "blogPost.readTime": "Lesezeit",
    "blogPost.minRemaining": "Min. übrig",
    "blogPost.relatedPosts": "Verwandte Artikel",
    "blogPost.toc.introduction": "Einleitung",
    "blogPost.toc.content": "Artikel",
    "blogPost.toc.author": "Über den Autor",
    "blogPost.toc.newsletter": "Newsletter",
    "blogPost.toc.related": "Ähnliche Beiträge",
    "blogPost.share": "Teilen",
    "blogPost.ctaTitle": "Bereit, Ihr Unternehmen mit KI zu transformieren?",
    "blogPost.ctaDesc": "Lassen Sie uns Ihnen helfen, KI-Lösungen zu implementieren, die echte Ergebnisse liefern.",
    "blogPost.ctaButton": "Kontakt aufnehmen",
    "blogPost.newsletter.title": "Kein Update verpassen",
    "blogPost.newsletter.desc": "Abonnieren Sie unseren Newsletter und erhalten Sie die neuesten KI-Insights direkt in Ihr Postfach.",
    "blogPost.newsletter.button": "Abonnieren",
    "blogPost.author.alexBio": "Alex leitet xeda.ai mit dem Fokus, die Lücke zwischen modernster KI-Forschung und praktischen Geschäftsanwendungen zu schließen. Mit über 10 Jahren Erfahrung in der Tech-Führung hilft er Unternehmen leidenschaftlich dabei, Wert durch intelligente Automatisierung zu erschließen.",
    "blogPost.author.mariaBio": "Maria bringt tiefe technische Expertise in Machine Learning und Software-Architektur zu xeda.ai. Sie ist spezialisiert auf das Design skalierbarer KI-Systeme und hat erfolgreiche Implementierungen für Unternehmen in ganz Europa geleitet.",
    "blogPost.post1.content": "Die ehrliche Antwort lautet: Es kommt darauf an — aber Sie können es abschätzen, bevor Sie einen Cent ausgeben. Die Kosten eines KI-Projekts hängen von vier Dingen ab: wie klar das Problem definiert ist, der Qualität und Verfügbarkeit Ihrer Daten, der Integrationstiefe und ob Sie einen laufenden Betrieb oder eine einmalige Entwicklung brauchen.\n\nEin Proof of Concept — genug, um zu zeigen, dass die Idee mit Ihren Daten funktioniert — beginnt typischerweise bei etwa 5.000 € und dauert einige Wochen. Er beantwortet eine Frage: Lohnt sich die echte Umsetzung?\n\nEin Produktiv-MVP — etwas, das Ihr Team oder Ihre Kunden tatsächlich nutzen — ist eine größere Investition, meist einige Wochen bis wenige Monate, je nach Integrationstiefe in Ihre bestehenden Tools.\n\nDer größte versteckte Kostenpunkt ist nicht das Modell, sondern die Datenarbeit und das Change-Management. Saubere, zugängliche Daten und ein Team, das den neuen Ablauf annimmt, zählen mehr als der Algorithmus.\n\nUnser Rat: Beginnen Sie mit einem Proof of Concept mit festem Umfang, messen Sie das Ergebnis an einer klaren Geschäftskennzahl und entscheiden Sie erst dann, was skaliert wird. Für KI sollten Sie nie einen Blankoscheck unterschreiben müssen.",
    "blogPost.post2.content": "Ja — Sie können KI einsetzen und DSGVO-konform bleiben. Aber das erfordert bewusste Entscheidungen, kein Wunschdenken.\n\nBeginnen Sie bei den Daten. Das sicherste KI-Projekt nutzt so wenige personenbezogene Daten wie möglich. Bevor etwas ein Modell erreicht, fragen Sie: Braucht dieser Anwendungsfall wirklich personenbezogene Daten — und lassen sie sich vorher anonymisieren oder pseudonymisieren?\n\nWissen Sie, wohin Ihre Daten fließen. Viele KI-Tools senden Daten an Server außerhalb der EU. Für sensible Anwendungsfälle ist das ein Problem. Optionen, die Sie in Kontrolle halten: EU-gehostete Modelle, Private-Cloud-Betrieb oder offene Modelle auf Ihrer eigenen Infrastruktur.\n\nDer EU AI Act kommt als zweite Ebene zur DSGVO hinzu. Er klassifiziert KI-Systeme nach Risiko, mit den strengsten Pflichten für Hochrisiko-Anwendungen, und verlangt Transparenz, wenn Menschen mit KI interagieren. Seine Pflichten greifen schrittweise bis 2025 und 2026.\n\nPraktische Schritte für den Mittelstand: Führen Sie ein Verzeichnis, wo KI personenbezogene Daten berührt, schließen Sie Auftragsverarbeitungsverträge mit Anbietern, bevorzugen Sie EU- oder On-Premise-Betrieb für alles Sensible und dokumentieren Sie Ihre Entscheidungen. Compliance ist kein Hindernis für KI — sie ist eine Rahmenbedingung, die Sie von Anfang an mitdenken.",
    "blogPost.post3.content": "Nicht jedes KI-Projekt rechnet sich schnell — aber einige zuverlässig. Hier sind fünf Einstiegspunkte, an denen kleine und mittlere Unternehmen am schnellsten einen Return sehen.\n\n1. Routineanrufe und Anfragen beantworten. Ein großer Teil eingehender Anrufe und E-Mails sind wiederkehrende Fragen. Ein KI-Assistent bearbeitet sie rund um die Uhr und leitet den Rest an einen Menschen weiter — so verlieren Sie keine Anfragen mehr nach Feierabend.\n\n2. Dokumenten- und Rechnungsverarbeitung. Daten aus Rechnungen, Formularen und PDFs von Hand zu erfassen ist langsam und fehleranfällig. KI macht aus Stunden manueller Eingabe Sekunden der Prüfung.\n\n3. Triage im Kundensupport. KI entwirft Antworten aus Ihrer bestehenden Wissensbasis und leitet Tickets an die richtige Person — kürzere Antwortzeiten ohne Qualitätsverlust.\n\n4. Interne Wissenssuche. Teams verlieren Zeit bei der Suche nach Informationen über viele Tools hinweg. Ein Copilot, der auf Ihren eigenen Dokumenten trainiert ist, antwortet in Sekunden.\n\n5. Entwürfe für Inhalte und Angebote. Angebote, Produktbeschreibungen und Routinekorrespondenz kann KI entwerfen und ein Mensch fertigstellen — schneller, konsistent und markenkonform.\n\nDas Muster: Wählen Sie eine Aufgabe, die häufig vorkommt, wenige Ausnahmen hat und messbar ist. Dort rechnet sich KI zuerst.",
    "blogPost.post4.content": "Die Skalierung von KI-Systemen von der Konzeptphase zur Produktion ist eine häufige Herausforderung.\n\nArchitektur ist von Anfang an wichtig. Planen Sie für Skalierbarkeit, auch wenn Sie sie noch nicht brauchen.\n\nMonitoring ist nicht optional. KI-Systeme können still versagen.\n\nVersionieren Sie alles. Modelle, Daten, Konfigurationen sollten reproduzierbar sein.",
    "blogPost.post5.content": "RAG und Fine-tuning sind zwei grundlegende Ansätze zur Anpassung von LLMs.\n\nRAG ruft relevante Dokumente ab und stellt sie als Kontext bereit. Ideal wenn sich Ihre Wissensbasis häufig ändert.\n\nFine-tuning modifiziert die Modellgewichte selbst. Exzellent für konsistenten Output und domänenspezifisches Verhalten.\n\nIn der Praxis kombinieren viele erfolgreiche Implementierungen beide Ansätze.",
    "blogPost.post6.content": "Der EU AI Act ist die umfassendste KI-Regulierung weltweit.\n\nDie Verordnung führt ein risikobasiertes Klassifizierungssystem ein. Hochrisiko-KI-Anwendungen unterliegen den strengsten Anforderungen.\n\nZeitpläne sind gestaffelt. Einige Bestimmungen gelten bereits, andere treten bis 2026 in Kraft.\n\nDokumentationsanforderungen sind umfangreich.\n\nUnsere Empfehlung: Führen Sie jetzt eine KI-Inventur durch und entwickeln Sie eine Compliance-Roadmap.",
    "footer.legal": "Rechtliches",
    "footer.privacy": "Datenschutz",
    "footer.terms": "AGB",
    "footer.impressum": "Impressum",
    "footer.rights": "Standort Deutschland.",
    "footer.newsletter.title": "Bleiben Sie informiert",
    "footer.newsletter.description": "Abonnieren Sie unseren Newsletter für KI-Einblicke und Updates.",
    "footer.newsletter.placeholder": "ihre@email.de",
    "footer.newsletter.invalidEmail": "Ungültige E-Mail",
    "footer.newsletter.enterValid": "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    "footer.newsletter.alreadySubscribed": "Bereits abonniert",
    "footer.newsletter.alreadyOnList": "Diese E-Mail ist bereits auf unserer Liste.",
    "footer.newsletter.subscribed": "Abonniert!",
    "footer.newsletter.thankYou": "Vielen Dank für Ihr Newsletter-Abonnement.",
    "footer.newsletter.error": "Etwas ist schiefgelaufen",
    "footer.newsletter.tryLater": "Bitte versuchen Sie es später erneut.",
  },
  fr: {
    // Header
    "nav.whatWeDo": "Nos Services",
    "nav.howWeWork": "Notre Méthode",
    "nav.forBusinesses": "Entreprises",
    "nav.forDevelopers": "Développeurs",
    "nav.caseStudies": "Études de Cas",
    "nav.pricing": "Tarifs",
    "nav.getInTouch": "Contact",
    // Hero
    "hero.badge": "Basé en Allemagne",
    "hero.title": "IA de production pour les",
    "hero.titleHighlight": "entreprises allemandes",
    "hero.subtitle": "Nous sommes un studio GenAI basé en Allemagne. Nous concevons et exploitons nos propres logiciels d'IA — et apportons la même rapidité et rigueur à votre MVP, automatisation ou copilote. Pas de battage, juste des solutions qui passent en production.",
    "hero.cta": "Réserver un audit IA gratuit",
    "hero.secondary": "Voir Ce Que Nous Créons",
    // Trust / compliance strip
    "trust.label": "Sécurité et conformité par défaut",
    "trust.gdpr.title": "Conforme au RGPD",
    "trust.gdpr.desc": "Conçu selon les normes européennes de protection des données.",
    "trust.encryption.title": "Chiffrement de bout en bout",
    "trust.encryption.desc": "Vos données sont chiffrées en transit et au repos.",
    "trust.deployment.title": "Sur site ou cloud privé",
    "trust.deployment.desc": "Déploiement dans votre propre environnement si nécessaire.",
    "trust.nda.title": "Sous NDA",
    "trust.nda.desc": "Chaque ingénieur travaille sous NDA et selon des protocoles de sécurité stricts.",
    // What We Do
    "whatWeDo.label": "Nos Services",
    "whatWeDo.title": "Produits & Implémentation IA",
    "whatWeDo.subtitle": "Nous combinons expertise technique approfondie et approche pragmatique pour créer des solutions IA qui génèrent une vraie valeur commerciale.",
    "whatWeDo.saas.title": "Produits SaaS GenAI",
    "whatWeDo.saas.desc": "Nous développons et exploitons nos propres produits logiciels basés sur l'IA. Du concept au marché.",
    "whatWeDo.mvp.title": "MVPs & Prototypes IA",
    "whatWeDo.mvp.desc": "Validez vos idées IA rapidement. Nous créons des prototypes fonctionnels pour tester vos hypothèses.",
    "whatWeDo.automation.title": "Automatisation IA",
    "whatWeDo.automation.desc": "Simplifiez le travail répétitif avec une automatisation intelligente intégrée à vos workflows.",
    // How We Work
    "howWeWork.label": "Notre Méthode",
    "howWeWork.title": "De l'Idée à la Production",
    "howWeWork.subtitle": "Notre processus minimise les risques et maximise l'apprentissage à chaque étape.",
    "howWeWork.step1.title": "Idée",
    "howWeWork.step1.desc": "Nous commençons par votre défi commercial. Ensemble, nous identifions où l'IA peut ajouter de la valeur.",
    "howWeWork.step2.title": "MVP",
    "howWeWork.step2.desc": "Construire vite, apprendre plus vite. Nous créons des prototypes qui valident les hypothèses en semaines.",
    "howWeWork.step3.title": "Marché",
    "howWeWork.step3.desc": "Tester avec de vrais utilisateurs. Nous vous aidons à recueillir des retours et affiner la solution.",
    "howWeWork.step4.title": "Échelle",
    "howWeWork.step4.desc": "Une fois validé, nous vous aidons à évoluer. Infrastructure de production et support continu.",
    // For Businesses
    "forBusinesses.label": "Pour les Entreprises",
    "forBusinesses.title": "Adopter l'IA en Confiance",
    "forBusinesses.subtitle": "Que vous exploriez l'IA pour la première fois ou que vous souhaitiez développer des initiatives existantes, nous apportons expertise technique et compréhension business.",
    "forBusinesses.description": "Nous travaillons avec des PME et des entreprises de tous secteurs. Notre approche est consultative.",
    "forBusinesses.transformation.title": "Transformation IA",
    "forBusinesses.transformation.desc": "Conseils stratégiques sur où et comment appliquer l'IA dans votre organisation.",
    "forBusinesses.copilots.title": "Copilotes Personnalisés",
    "forBusinesses.copilots.desc": "Assistants IA adaptés à vos workflows. Du support client aux opérations internes.",
    "forBusinesses.automation.title": "Automatisation des Processus",
    "forBusinesses.automation.desc": "Automatisez le traitement de documents et les tâches répétitives.",
    "forBusinesses.enablement.title": "Formation d'Équipe",
    "forBusinesses.enablement.desc": "Formez votre équipe à travailler efficacement avec les outils IA.",
    // For Developers
    "forDevelopers.label": "Pour les Développeurs",
    "forDevelopers.title": "Construire des Solutions IA Ensemble",
    "forDevelopers.subtitle": "Nous recherchons des développeurs qualifiés pour travailler sur des projets IA stimulants. Que ce soit en freelance ou en collaboration continue, parlons-en.",
    "forDevelopers.benefit1": "Projets collaboratifs avec des ingénieurs IA expérimentés",
    "forDevelopers.benefit2": "Stack moderne : Python, TypeScript, cloud-native",
    "forDevelopers.benefit3": "Conditions équitables et communication transparente",
    "forDevelopers.benefit4": "Problèmes intéressants en GenAI, LLMs et MLOps",
    "forDevelopers.cta": "Nous Contacter",
    // Pricing
    "pricing.title": "Modèles d'Engagement Flexibles",
    "pricing.subtitle": "Choisissez le forfait adapté à vos besoins ou discutons d'une solution personnalisée",
    "pricing.popular": "Plus Populaire",
    "pricing.cta": "Commencer",
    "pricing.note": "Tous les forfaits incluent une consultation initiale et un cadrage projet gratuits.",
    "pricing.starter.name": "Starter",
    "pricing.starter.desc": "Parfait pour explorer les possibilités de l'IA",
    "pricing.starter.price": "À partir de 5 000 €",
    "pricing.starter.period": "par projet",
    "pricing.starter.feature1": "Évaluation de faisabilité IA",
    "pricing.starter.feature2": "Développement de preuve de concept",
    "pricing.starter.feature3": "Jusqu'à 4 semaines",
    "pricing.starter.feature4": "Documentation technique",
    "pricing.starter.feature5": "1 cycle de révision",
    "pricing.growth.name": "Croissance",
    "pricing.growth.desc": "Pour les entreprises prêtes à évoluer avec l'IA",
    "pricing.growth.price": "À partir de 15 000 €",
    "pricing.growth.period": "par projet",
    "pricing.growth.feature1": "Développement MVP complet",
    "pricing.growth.feature2": "Intégration de modèle IA personnalisé",
    "pricing.growth.feature3": "Jusqu'à 8 semaines",
    "pricing.growth.feature4": "Formation d'équipe incluse",
    "pricing.growth.feature5": "3 cycles de révision",
    "pricing.growth.feature6": "30 jours de support post-lancement",
    "pricing.enterprise.name": "Entreprise",
    "pricing.enterprise.desc": "Transformation IA complète",
    "pricing.enterprise.price": "Sur mesure",
    "pricing.enterprise.period": "adapté à vos besoins",
    "pricing.enterprise.feature1": "Solution IA de bout en bout",
    "pricing.enterprise.feature2": "Équipe projet dédiée",
    "pricing.enterprise.feature3": "Calendrier flexible",
    "pricing.enterprise.feature4": "Option de déploiement sur site",
    "pricing.enterprise.feature5": "Révisions illimitées",
    "pricing.enterprise.feature6": "Support et maintenance continus",
    "pricing.enterprise.feature7": "Garanties SLA",
    // Why Us
    "whyUs.label": "Pourquoi Nous",
    "whyUs.title": "Construits Différemment",
    "whyUs.subtitle": "Nous sommes une petite équipe focalisée qui prend fierté à livrer un travail exceptionnel.",
    "whyUs.reason1.title": "Exécution par les Fondateurs",
    "whyUs.reason1.desc": "Vous travaillez directement avec les fondateurs. Pas de gestionnaires de compte, pas de couches.",
    "whyUs.reason2.title": "Rapide & Focalisé",
    "whyUs.reason2.desc": "Nous avançons vite mais délibérément. Petite équipe, boucles de feedback serrées.",
    "whyUs.reason3.title": "Vraie Expertise IA",
    "whyUs.reason3.desc": "Nous construisons avec l'IA chaque jour. Pas des consultants—des ingénieurs qui implémentent en production.",
    // FAQ
    "faq.title": "Questions Fréquentes",
    "faq.subtitle": "Des questions ? Nous avons les réponses.",
    "faq.q1": "Quels types de solutions IA propose xeda.ai ?",
    "faq.a1": "Nous nous spécialisons dans les produits SaaS GenAI, les MVPs IA, les solutions d'automatisation, le conseil en transformation IA et les copilotes personnalisés.",
    "faq.q2": "Combien de temps dure un projet IA typique ?",
    "faq.a2": "Les délais varient selon la complexité. Un MVP IA peut être livré en 4-8 semaines, tandis que les projets de transformation prennent 3-6 mois.",
    "faq.q3": "Ai-je besoin d'expertise technique pour travailler avec xeda.ai ?",
    "faq.a3": "Pas du tout. Nous gérons tous les aspects techniques du projet et travaillons avec vos parties prenantes.",
    "faq.q4": "Comment assurez-vous la sécurité et la confidentialité des données ?",
    "faq.a4": "La sécurité est primordiale. Nous suivons la conformité RGPD et implémentons le chiffrement de bout en bout.",
    "faq.q5": "Qu'est-ce qui différencie xeda.ai des autres agences IA ?",
    "faq.a5": "Nous combinons la précision de l'ingénierie allemande avec une expertise IA de pointe. Notre équipe construit des systèmes de production.",
    "faq.q6": "Proposez-vous un support continu après la fin du projet ?",
    "faq.a6": "Oui, nous proposons des packages de support et maintenance flexibles. Beaucoup de clients travaillent avec nous en continu.",
    // Team
    "team.label": "Notre Équipe",
    "team.title": "Rencontrez le Fondateur",
    "team.founder.role": "Fondateur",
    "team.subtitle": "Une petite équipe dévouée avec une expertise approfondie en IA et une passion pour créer des produits exceptionnels.",
    "team.valuesTitle": "Nos Valeurs",
    "team.alex.role": "Co-fondateur & CEO",
    "team.alex.bio": "10+ ans de leadership tech. A construit des produits IA dans des entreprises leaders. Passionné par les solutions IA pratiques.",
    "team.maria.role": "Co-fondatrice & CTO",
    "team.maria.bio": "Ingénieure ML experte en LLMs et systèmes de production. Ex-ingénieure senior dans des labos de recherche IA.",
    "team.value1.title": "Intégrité",
    "team.value1.desc": "Nous sommes honnêtes sur ce que l'IA peut et ne peut pas faire.",
    "team.value2.title": "Innovation",
    "team.value2.desc": "Nous restons à la pointe tout en nous concentrant sur les applications pratiques.",
    "team.value3.title": "Partenariat",
    "team.value3.desc": "Nous travaillons aux côtés de votre équipe, pas juste comme prestataires externes.",
    "team.value4.title": "Excellence",
    "team.value4.desc": "Nous prenons fierté à livrer un travail de qualité qui dépasse les attentes.",
    // Contact
    "contact.title": "Parlons-en",
    "contact.subtitle": "Que vous exploriez les possibilités de l'IA, prêt à démarrer un projet, ou intéressé par une collaboration—nous aimerions vous entendre.",
    "contact.name": "Nom",
    "contact.namePlaceholder": "Votre nom",
    "contact.email": "Email",
    "contact.emailPlaceholder": "vous@entreprise.com",
    "contact.company": "Entreprise",
    "contact.companyPlaceholder": "Votre entreprise (optionnel)",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Parlez-nous de votre projet ou comment nous pouvons vous aider...",
    "contact.send": "Envoyer le Message",
    "contact.sending": "Envoi en cours...",
    "contact.orEmail": "Ou envoyez-nous un email à",
    "contact.responseTime": "Nous répondons généralement sous un jour ouvré.",
    "contact.success.title": "Message envoyé !",
    "contact.success.description": "Nous vous recontacterons sous un jour ouvré.",
    "contact.error.validation": "Erreur de validation",
    "contact.error.general": "Quelque chose s'est mal passé",
    "contact.error.tryAgain": "Veuillez réessayer ou nous envoyer un email directement.",
    "contact.error.nameRequired": "Le nom est requis",
    "contact.error.nameTooLong": "Le nom doit faire moins de 100 caractères",
    "contact.error.invalidEmail": "Adresse email invalide",
    "contact.error.emailTooLong": "L'email doit faire moins de 255 caractères",
    "contact.error.companyTooLong": "L'entreprise doit faire moins de 100 caractères",
    "contact.error.messageRequired": "Le message est requis",
    "contact.error.messageTooLong": "Le message doit faire moins de 2000 caractères",
    // Footer
    "footer.description": "Agence GenAI allemande construisant des solutions intelligentes pour les entreprises.",
    "footer.careers": "Carrières — nous recrutons des développeurs →",
    // Blog
    "blog.label": "Actualités",
    "blog.title": "Insights & Actualités IA",
    "blog.subtitle": "Restez informé des dernières tendances, meilleures pratiques et insights de nos experts IA.",
    "blog.readMore": "Lire la suite",
    "blog.viewAll": "Voir tous les articles",
    // Blog Page
    "blogPage.backHome": "Retour à l'accueil",
    "blogPage.searchPlaceholder": "Rechercher des articles...",
    "blogPage.allCategories": "Tous",
    "blogPage.noResults": "Aucun article trouvé.",
    "blogPage.post4.title": "Construire une infrastructure IA évolutive : Leçons de la production",
    "blogPage.post4.excerpt": "Insights clés du déploiement de systèmes IA à grande échelle, incluant patterns d'architecture et optimisation des coûts.",
    "blogPage.post5.title": "RAG vs Fine-tuning : Choisir la bonne approche pour votre LLM",
    "blogPage.post5.excerpt": "Une plongée technique dans RAG et le fine-tuning avec des conseils pratiques.",
    "blogPage.post6.title": "Régulation de l'IA en Europe : Ce que 2025 réserve aux entreprises",
    "blogPage.post6.excerpt": "Un aperçu des réglementations IA à venir dans l'UE et comment les entreprises peuvent se préparer.",
    // Blog Post Page
    "blogPost.notFound": "Article non trouvé",
    "blogPost.notFoundDesc": "L'article que vous recherchez n'existe pas ou a été déplacé.",
    "blogPost.backToBlog": "Retour au Blog",
    "blogPost.readTime": "de lecture",
    "blogPost.minRemaining": "min restantes",
    "blogPost.relatedPosts": "Articles connexes",
    "blogPost.toc.introduction": "Introduction",
    "blogPost.toc.content": "Article",
    "blogPost.toc.author": "À propos de l'auteur",
    "blogPost.toc.newsletter": "Newsletter",
    "blogPost.toc.related": "Articles similaires",
    "blogPost.share": "Partager",
    "blogPost.ctaTitle": "Prêt à transformer votre entreprise avec l'IA ?",
    "blogPost.ctaDesc": "Laissez-nous vous aider à implémenter des solutions IA qui livrent de vrais résultats.",
    "blogPost.ctaButton": "Nous contacter",
    "blogPost.newsletter.title": "Ne manquez aucune mise à jour",
    "blogPost.newsletter.desc": "Abonnez-vous à notre newsletter et recevez les derniers insights IA dans votre boîte mail.",
    "blogPost.newsletter.button": "S'abonner",
    "blogPost.author.alexBio": "Alex dirige xeda.ai en se concentrant sur le rapprochement entre la recherche IA de pointe et les applications commerciales pratiques. Avec plus de 10 ans d'expérience en leadership technologique, il est passionné par l'aide aux entreprises pour libérer leur valeur grâce à l'automatisation intelligente.",
    "blogPost.author.mariaBio": "Maria apporte une expertise technique approfondie en apprentissage automatique et architecture logicielle à xeda.ai. Elle se spécialise dans la conception de systèmes IA évolutifs et a dirigé des implémentations réussies pour des entreprises à travers l'Europe.",
    "blogPost.post4.content": "Passer d'un proof-of-concept à la production est un défi fréquent.\n\nL'architecture compte dès le premier jour. Concevez pour l'évolutivité.\n\nLe monitoring n'est pas optionnel. Les systèmes IA peuvent échouer silencieusement.\n\nVersionnez tout. Modèles, données, configurations.",
    "blogPost.post5.content": "RAG et fine-tuning sont deux approches fondamentales pour personnaliser les LLMs.\n\nRAG récupère des documents pertinents et les fournit comme contexte. Idéal quand votre base de connaissances change fréquemment.\n\nLe fine-tuning modifie les poids du modèle. Excellent pour un output cohérent.\n\nEn pratique, beaucoup combinent les deux approches.",
    "blogPost.post6.content": "Le AI Act européen est la réglementation IA la plus complète au monde.\n\nLa réglementation introduit un système de classification basé sur les risques.\n\nLes délais sont échelonnés. Certaines dispositions sont déjà en vigueur.\n\nLes exigences de documentation sont substantielles.\n\nNotre recommandation : réalisez un inventaire IA maintenant.",
    "footer.legal": "Légal",
    "footer.privacy": "Politique de Confidentialité",
    "footer.terms": "Conditions d'Utilisation",
    "footer.impressum": "Mentions Légales",
    "footer.rights": "Basé en Allemagne.",
    "footer.newsletter.title": "Restez Informé",
    "footer.newsletter.description": "Abonnez-vous à notre newsletter pour des insights IA et des mises à jour.",
    "footer.newsletter.placeholder": "votre@email.com",
    "footer.newsletter.invalidEmail": "Email invalide",
    "footer.newsletter.enterValid": "Veuillez entrer une adresse email valide.",
    "footer.newsletter.alreadySubscribed": "Déjà abonné",
    "footer.newsletter.alreadyOnList": "Cet email est déjà sur notre liste.",
    "footer.newsletter.subscribed": "Abonné !",
    "footer.newsletter.thankYou": "Merci de vous être abonné à notre newsletter.",
    "footer.newsletter.error": "Quelque chose s'est mal passé",
    "footer.newsletter.tryLater": "Veuillez réessayer plus tard.",
  },
  es: {
    // Header
    "nav.whatWeDo": "Qué Hacemos",
    "nav.howWeWork": "Cómo Trabajamos",
    "nav.forBusinesses": "Empresas",
    "nav.forDevelopers": "Desarrolladores",
    "nav.caseStudies": "Casos de Éxito",
    "nav.pricing": "Precios",
    "nav.getInTouch": "Contacto",
    // Hero
    "hero.badge": "Con sede en Alemania",
    "hero.title": "IA de producción para",
    "hero.titleHighlight": "empresas alemanas",
    "hero.subtitle": "Somos un estudio de GenAI con sede en Alemania. Creamos y operamos nuestro propio software de IA — y aportamos la misma velocidad y rigor a tu MVP, automatización o copiloto. Sin exageraciones, solo soluciones que llegan a producción.",
    "hero.cta": "Reservar una auditoría de IA gratis",
    "hero.secondary": "Ver Lo Que Creamos",
    // Trust / compliance strip
    "trust.label": "Seguridad y cumplimiento por defecto",
    "trust.gdpr.title": "Cumple con el RGPD",
    "trust.gdpr.desc": "Desarrollado según los estándares europeos de protección de datos.",
    "trust.encryption.title": "Cifrado de extremo a extremo",
    "trust.encryption.desc": "Tus datos se cifran en tránsito y en reposo.",
    "trust.deployment.title": "On-premise o nube privada",
    "trust.deployment.desc": "Despliegue en tu propio entorno cuando lo necesites.",
    "trust.nda.title": "Bajo NDA",
    "trust.nda.desc": "Cada ingeniero trabaja bajo NDA y estrictos protocolos de seguridad.",
    // What We Do
    "whatWeDo.label": "Qué Hacemos",
    "whatWeDo.title": "Productos e Implementación de IA",
    "whatWeDo.subtitle": "Combinamos experiencia técnica profunda con un enfoque pragmático para crear soluciones de IA que generan valor real.",
    "whatWeDo.saas.title": "Productos SaaS GenAI",
    "whatWeDo.saas.desc": "Desarrollamos y operamos nuestros propios productos de software basados en IA. Del concepto al mercado.",
    "whatWeDo.mvp.title": "MVPs y Prototipos de IA",
    "whatWeDo.mvp.desc": "Valida tus ideas de IA rápidamente. Creamos prototipos funcionales para probar hipótesis.",
    "whatWeDo.automation.title": "Automatización con IA",
    "whatWeDo.automation.desc": "Optimiza el trabajo repetitivo con automatización inteligente integrada en tus flujos.",
    // How We Work
    "howWeWork.label": "Cómo Trabajamos",
    "howWeWork.title": "De la Idea a Producción",
    "howWeWork.subtitle": "Nuestro proceso minimiza riesgos y maximiza el aprendizaje en cada etapa.",
    "howWeWork.step1.title": "Idea",
    "howWeWork.step1.desc": "Comenzamos con tu desafío de negocio. Juntos identificamos dónde la IA puede agregar valor.",
    "howWeWork.step2.title": "MVP",
    "howWeWork.step2.desc": "Construir rápido, aprender más rápido. Creamos prototipos que validan hipótesis en semanas.",
    "howWeWork.step3.title": "Mercado",
    "howWeWork.step3.desc": "Probar con usuarios reales. Te ayudamos a recopilar feedback y refinar la solución.",
    "howWeWork.step4.title": "Escalar",
    "howWeWork.step4.desc": "Una vez validado, te ayudamos a escalar. Infraestructura de producción y soporte continuo.",
    // For Businesses
    "forBusinesses.label": "Para Empresas",
    "forBusinesses.title": "Adoptar IA con Confianza",
    "forBusinesses.subtitle": "Ya sea que explores la IA por primera vez o quieras escalar iniciativas existentes, proporcionamos la profundidad técnica y comprensión de negocio.",
    "forBusinesses.description": "Trabajamos con PYMEs y empresas de todos los sectores. Nuestro enfoque es consultivo.",
    "forBusinesses.transformation.title": "Transformación IA",
    "forBusinesses.transformation.desc": "Orientación estratégica sobre dónde y cómo aplicar IA en tu organización.",
    "forBusinesses.copilots.title": "Copilotos Personalizados",
    "forBusinesses.copilots.desc": "Asistentes de IA adaptados a tus flujos de trabajo. Desde soporte al cliente hasta operaciones internas.",
    "forBusinesses.automation.title": "Automatización de Procesos",
    "forBusinesses.automation.desc": "Automatiza el procesamiento de documentos y tareas repetitivas.",
    "forBusinesses.enablement.title": "Capacitación de Equipo",
    "forBusinesses.enablement.desc": "Capacita a tu equipo para trabajar eficazmente con herramientas de IA.",
    // For Developers
    "forDevelopers.label": "Para Desarrolladores",
    "forDevelopers.title": "Construir Soluciones de IA Juntos",
    "forDevelopers.subtitle": "Siempre buscamos desarrolladores cualificados para trabajar en proyectos de IA desafiantes. Ya sea trabajo freelance o colaboración continua, hablemos.",
    "forDevelopers.benefit1": "Proyectos colaborativos con ingenieros de IA experimentados",
    "forDevelopers.benefit2": "Stack moderno: Python, TypeScript, cloud-native",
    "forDevelopers.benefit3": "Condiciones justas y comunicación transparente",
    "forDevelopers.benefit4": "Problemas interesantes en GenAI, LLMs y MLOps",
    "forDevelopers.cta": "Contáctanos",
    // Pricing
    "pricing.title": "Modelos de Compromiso Flexibles",
    "pricing.subtitle": "Elige el paquete que se adapte a tus necesidades o discutamos una solución personalizada",
    "pricing.popular": "Más Popular",
    "pricing.cta": "Empezar",
    "pricing.note": "Todos los paquetes incluyen consulta inicial y definición del proyecto sin costo.",
    "pricing.starter.name": "Starter",
    "pricing.starter.desc": "Perfecto para explorar posibilidades de IA",
    "pricing.starter.price": "Desde 5.000 €",
    "pricing.starter.period": "por proyecto",
    "pricing.starter.feature1": "Evaluación de viabilidad de IA",
    "pricing.starter.feature2": "Desarrollo de prueba de concepto",
    "pricing.starter.feature3": "Hasta 4 semanas",
    "pricing.starter.feature4": "Documentación técnica",
    "pricing.starter.feature5": "1 ronda de revisión",
    "pricing.growth.name": "Crecimiento",
    "pricing.growth.desc": "Para empresas listas para escalar con IA",
    "pricing.growth.price": "Desde 15.000 €",
    "pricing.growth.period": "por proyecto",
    "pricing.growth.feature1": "Desarrollo completo de MVP",
    "pricing.growth.feature2": "Integración de modelo IA personalizado",
    "pricing.growth.feature3": "Hasta 8 semanas",
    "pricing.growth.feature4": "Capacitación de equipo incluida",
    "pricing.growth.feature5": "3 rondas de revisión",
    "pricing.growth.feature6": "30 días de soporte post-lanzamiento",
    "pricing.enterprise.name": "Empresa",
    "pricing.enterprise.desc": "Transformación IA integral",
    "pricing.enterprise.price": "Personalizado",
    "pricing.enterprise.period": "adaptado a tus necesidades",
    "pricing.enterprise.feature1": "Solución IA de extremo a extremo",
    "pricing.enterprise.feature2": "Equipo de proyecto dedicado",
    "pricing.enterprise.feature3": "Cronograma flexible",
    "pricing.enterprise.feature4": "Opción de despliegue on-premise",
    "pricing.enterprise.feature5": "Revisiones ilimitadas",
    "pricing.enterprise.feature6": "Soporte y mantenimiento continuo",
    "pricing.enterprise.feature7": "Garantías SLA",
    // Why Us
    "whyUs.label": "Por Qué Nosotros",
    "whyUs.title": "Construidos Diferente",
    "whyUs.subtitle": "Somos un equipo pequeño y enfocado que se enorgullece de entregar trabajo excepcional.",
    "whyUs.reason1.title": "Ejecución por Fundadores",
    "whyUs.reason1.desc": "Trabajas directamente con los fundadores. Sin gestores de cuenta, sin capas.",
    "whyUs.reason2.title": "Rápido y Enfocado",
    "whyUs.reason2.desc": "Nos movemos rápido pero deliberadamente. Equipo pequeño, ciclos de feedback cortos.",
    "whyUs.reason3.title": "Experiencia Real en IA",
    "whyUs.reason3.desc": "Construimos con IA todos los días. No consultores—ingenieros que implementan en producción.",
    // FAQ
    "faq.title": "Preguntas Frecuentes",
    "faq.subtitle": "¿Tienes preguntas? Tenemos respuestas.",
    "faq.q1": "¿Qué tipos de soluciones de IA ofrece xeda.ai?",
    "faq.a1": "Nos especializamos en productos SaaS GenAI, MVPs de IA, soluciones de automatización, consultoría de transformación IA y copilotos personalizados.",
    "faq.q2": "¿Cuánto tiempo lleva un proyecto de IA típico?",
    "faq.a2": "Los plazos varían según la complejidad. Un MVP de IA puede entregarse en 4-8 semanas, mientras que proyectos de transformación toman 3-6 meses.",
    "faq.q3": "¿Necesito experiencia técnica para trabajar con xeda.ai?",
    "faq.a3": "Para nada. Manejamos todos los aspectos técnicos del proyecto y trabajamos con tus stakeholders.",
    "faq.q4": "¿Cómo aseguran la seguridad y privacidad de datos?",
    "faq.a4": "La seguridad es primordial. Seguimos el cumplimiento RGPD e implementamos cifrado de extremo a extremo.",
    "faq.q5": "¿Qué diferencia a xeda.ai de otras agencias de IA?",
    "faq.a5": "Combinamos la precisión de la ingeniería alemana con experiencia en IA de vanguardia. Nuestro equipo construye sistemas de producción.",
    "faq.q6": "¿Ofrecen soporte continuo después de completar el proyecto?",
    "faq.a6": "Sí, ofrecemos paquetes flexibles de soporte y mantenimiento. Muchos clientes trabajan con nosotros de forma continua.",
    // Team
    "team.label": "Nuestro Equipo",
    "team.title": "Conoce al Fundador",
    "team.founder.role": "Fundador",
    "team.subtitle": "Un equipo pequeño y dedicado con profunda experiencia en IA y pasión por crear productos excepcionales.",
    "team.valuesTitle": "Nuestros Valores",
    "team.alex.role": "Cofundador & CEO",
    "team.alex.bio": "10+ años en liderazgo tech. Anteriormente creó productos de IA en empresas líderes. Apasionado por soluciones de IA prácticas.",
    "team.maria.role": "Cofundadora & CTO",
    "team.maria.bio": "Ingeniera ML experta en LLMs y sistemas de producción. Ex-ingeniera senior en laboratorios de investigación de IA.",
    "team.value1.title": "Integridad",
    "team.value1.desc": "Somos honestos sobre lo que la IA puede y no puede hacer.",
    "team.value2.title": "Innovación",
    "team.value2.desc": "Nos mantenemos a la vanguardia enfocándonos en aplicaciones prácticas.",
    "team.value3.title": "Colaboración",
    "team.value3.desc": "Trabajamos junto a tu equipo, no solo como proveedores externos.",
    "team.value4.title": "Excelencia",
    "team.value4.desc": "Nos enorgullecemos de entregar trabajo de calidad que supera expectativas.",
    // Contact
    "contact.title": "Hablemos",
    "contact.subtitle": "Ya sea que explores posibilidades de IA, listo para iniciar un proyecto, o interesado en colaborar—nos encantaría saber de ti.",
    "contact.name": "Nombre",
    "contact.namePlaceholder": "Tu nombre",
    "contact.email": "Email",
    "contact.emailPlaceholder": "tu@empresa.com",
    "contact.company": "Empresa",
    "contact.companyPlaceholder": "Tu empresa (opcional)",
    "contact.message": "Mensaje",
    "contact.messagePlaceholder": "Cuéntanos sobre tu proyecto o cómo podemos ayudar...",
    "contact.send": "Enviar Mensaje",
    "contact.sending": "Enviando...",
    "contact.orEmail": "O envíanos un email a",
    "contact.responseTime": "Normalmente respondemos en un día hábil.",
    "contact.success.title": "¡Mensaje enviado!",
    "contact.success.description": "Te contactaremos en un día hábil.",
    "contact.error.validation": "Error de validación",
    "contact.error.general": "Algo salió mal",
    "contact.error.tryAgain": "Por favor intenta de nuevo o envíanos un email directamente.",
    "contact.error.nameRequired": "El nombre es requerido",
    "contact.error.nameTooLong": "El nombre debe tener menos de 100 caracteres",
    "contact.error.invalidEmail": "Dirección de email inválida",
    "contact.error.emailTooLong": "El email debe tener menos de 255 caracteres",
    "contact.error.companyTooLong": "La empresa debe tener menos de 100 caracteres",
    "contact.error.messageRequired": "El mensaje es requerido",
    "contact.error.messageTooLong": "El mensaje debe tener menos de 2000 caracteres",
    // Footer
    "footer.description": "Agencia GenAI alemana construyendo soluciones inteligentes para empresas.",
    "footer.careers": "Carreras — buscamos desarrolladores →",
    // Blog
    "blog.label": "Insights",
    "blog.title": "Insights y Novedades de IA",
    "blog.subtitle": "Mantente informado sobre las últimas tendencias, mejores prácticas e insights de nuestros expertos en IA.",
    "blog.readMore": "Leer más",
    "blog.viewAll": "Ver todos los artículos",
    // Blog Page
    "blogPage.backHome": "Volver al inicio",
    "blogPage.searchPlaceholder": "Buscar artículos...",
    "blogPage.allCategories": "Todos",
    "blogPage.noResults": "No se encontraron artículos.",
    "blogPage.post4.title": "Construir infraestructura IA escalable: Lecciones de producción",
    "blogPage.post4.excerpt": "Insights clave del despliegue de sistemas IA a escala, incluyendo patrones de arquitectura y optimización de costos.",
    "blogPage.post5.title": "RAG vs Fine-tuning: Elegir el enfoque correcto para tu LLM",
    "blogPage.post5.excerpt": "Un análisis técnico profundo de RAG y fine-tuning con orientación práctica.",
    "blogPage.post6.title": "Regulación de IA en Europa: Lo que 2025 trae para las empresas",
    "blogPage.post6.excerpt": "Una visión general de las próximas regulaciones de IA en la UE y cómo las empresas pueden prepararse.",
    // Blog Post Page
    "blogPost.notFound": "Artículo no encontrado",
    "blogPost.notFoundDesc": "El artículo que buscas no existe o ha sido movido.",
    "blogPost.backToBlog": "Volver al Blog",
    "blogPost.readTime": "de lectura",
    "blogPost.minRemaining": "min restantes",
    "blogPost.relatedPosts": "Artículos relacionados",
    "blogPost.toc.introduction": "Introducción",
    "blogPost.toc.content": "Artículo",
    "blogPost.toc.author": "Sobre el Autor",
    "blogPost.toc.newsletter": "Boletín",
    "blogPost.toc.related": "Artículos similares",
    "blogPost.share": "Compartir",
    "blogPost.ctaTitle": "¿Listo para transformar tu negocio con IA?",
    "blogPost.ctaDesc": "Permítenos ayudarte a implementar soluciones de IA que entreguen resultados reales.",
    "blogPost.ctaButton": "Contáctanos",
    "blogPost.newsletter.title": "No te pierdas ninguna actualización",
    "blogPost.newsletter.desc": "Suscríbete a nuestro newsletter y recibe los últimos insights de IA en tu bandeja de entrada.",
    "blogPost.newsletter.button": "Suscribirse",
    "blogPost.author.alexBio": "Alex lidera xeda.ai con un enfoque en cerrar la brecha entre la investigación de IA de vanguardia y las aplicaciones comerciales prácticas. Con más de 10 años de experiencia en liderazgo tecnológico, le apasiona ayudar a las empresas a desbloquear valor a través de la automatización inteligente.",
    "blogPost.author.mariaBio": "Maria aporta una profunda experiencia técnica en aprendizaje automático y arquitectura de software a xeda.ai. Se especializa en diseñar sistemas de IA escalables y ha liderado implementaciones exitosas para empresas en toda Europa.",
    "blogPost.post4.content": "Escalar sistemas de IA de prueba de concepto a producción es un desafío común.\n\nLa arquitectura importa desde el día uno. Diseña para escalabilidad.\n\nEl monitoreo no es opcional. Los sistemas de IA pueden fallar silenciosamente.\n\nVersiona todo. Modelos, datos, configuraciones.",
    "blogPost.post5.content": "RAG y fine-tuning son dos enfoques fundamentales para personalizar LLMs.\n\nRAG recupera documentos relevantes y los proporciona como contexto. Ideal cuando tu base de conocimiento cambia frecuentemente.\n\nFine-tuning modifica los pesos del modelo. Excelente para output consistente.\n\nEn la práctica, muchos combinan ambos enfoques.",
    "blogPost.post6.content": "El AI Act de la UE es la regulación de IA más completa a nivel global.\n\nLa regulación introduce un sistema de clasificación basado en riesgos.\n\nLos plazos son escalonados. Algunas disposiciones ya están vigentes.\n\nLos requisitos de documentación son sustanciales.\n\nNuestra recomendación: realiza un inventario de IA ahora.",
    "footer.legal": "Legal",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos de Servicio",
    "footer.impressum": "Aviso Legal",
    "footer.rights": "Con sede en Alemania.",
    "footer.newsletter.title": "Mantente Informado",
    "footer.newsletter.description": "Suscríbete a nuestro newsletter para insights de IA y actualizaciones.",
    "footer.newsletter.placeholder": "tu@email.com",
    "footer.newsletter.invalidEmail": "Email inválido",
    "footer.newsletter.enterValid": "Por favor ingresa una dirección de email válida.",
    "footer.newsletter.alreadySubscribed": "Ya suscrito",
    "footer.newsletter.alreadyOnList": "Este email ya está en nuestra lista.",
    "footer.newsletter.subscribed": "¡Suscrito!",
    "footer.newsletter.thankYou": "Gracias por suscribirte a nuestro newsletter.",
    "footer.newsletter.error": "Algo salió mal",
    "footer.newsletter.tryLater": "Por favor intenta más tarde.",
  },
  it: {
    // Header
    "nav.whatWeDo": "Cosa Facciamo",
    "nav.howWeWork": "Come Lavoriamo",
    "nav.forBusinesses": "Per Aziende",
    "nav.forDevelopers": "Per Sviluppatori",
    "nav.caseStudies": "Casi Studio",
    "nav.pricing": "Prezzi",
    "nav.getInTouch": "Contatti",
    // Hero
    "hero.badge": "Con sede in Germania",
    "hero.title": "IA di produzione per le",
    "hero.titleHighlight": "aziende tedesche",
    "hero.subtitle": "Siamo uno studio GenAI con sede in Germania. Sviluppiamo e gestiamo software IA di nostra proprietà — e portiamo la stessa velocità e cura nel tuo MVP, automazione o copilota. Niente hype, solo soluzioni che vanno in produzione.",
    "hero.cta": "Prenota un audit AI gratuito",
    "hero.secondary": "Scopri Cosa Creiamo",
    // Trust / compliance strip
    "trust.label": "Sicurezza e conformità di default",
    "trust.gdpr.title": "Conforme al GDPR",
    "trust.gdpr.desc": "Sviluppato secondo gli standard europei di protezione dei dati.",
    "trust.encryption.title": "Crittografia end-to-end",
    "trust.encryption.desc": "I tuoi dati sono crittografati in transito e a riposo.",
    "trust.deployment.title": "On-premise o cloud privato",
    "trust.deployment.desc": "Deployment nel tuo ambiente quando serve.",
    "trust.nda.title": "Sotto NDA",
    "trust.nda.desc": "Ogni ingegnere lavora sotto NDA e rigorosi protocolli di sicurezza.",
    // What We Do
    "whatWeDo.label": "Cosa Facciamo",
    "whatWeDo.title": "Prodotti e Implementazione IA",
    "whatWeDo.subtitle": "Combiniamo profonda competenza tecnica con un approccio pragmatico per creare soluzioni IA che generano valore reale.",
    "whatWeDo.saas.title": "Prodotti SaaS GenAI",
    "whatWeDo.saas.desc": "Sviluppiamo e gestiamo i nostri prodotti software basati su IA. Dal concetto al mercato.",
    "whatWeDo.mvp.title": "MVP e Prototipi IA",
    "whatWeDo.mvp.desc": "Valida le tue idee IA rapidamente. Creiamo prototipi funzionali per testare le ipotesi.",
    "whatWeDo.automation.title": "Automazione con IA",
    "whatWeDo.automation.desc": "Ottimizza il lavoro ripetitivo con automazione intelligente integrata nei tuoi flussi.",
    // How We Work
    "howWeWork.label": "Come Lavoriamo",
    "howWeWork.title": "Dall'Idea alla Produzione",
    "howWeWork.subtitle": "Il nostro processo minimizza i rischi e massimizza l'apprendimento in ogni fase.",
    "howWeWork.step1.title": "Idea",
    "howWeWork.step1.desc": "Iniziamo dalla tua sfida aziendale. Insieme identifichiamo dove l'IA può aggiungere valore.",
    "howWeWork.step2.title": "MVP",
    "howWeWork.step2.desc": "Costruire veloce, imparare più veloce. Creiamo prototipi che validano ipotesi in settimane.",
    "howWeWork.step3.title": "Mercato",
    "howWeWork.step3.desc": "Testare con utenti reali. Ti aiutiamo a raccogliere feedback e perfezionare la soluzione.",
    "howWeWork.step4.title": "Scala",
    "howWeWork.step4.desc": "Una volta validato, ti aiutiamo a scalare. Infrastruttura di produzione e supporto continuo.",
    // For Businesses
    "forBusinesses.label": "Per le Aziende",
    "forBusinesses.title": "Adottare l'IA con Fiducia",
    "forBusinesses.subtitle": "Che tu stia esplorando l'IA per la prima volta o voglia scalare iniziative esistenti, forniamo la profondità tecnica e la comprensione del business.",
    "forBusinesses.description": "Lavoriamo con PMI e aziende di tutti i settori. Il nostro approccio è consulenziale.",
    "forBusinesses.transformation.title": "Trasformazione IA",
    "forBusinesses.transformation.desc": "Guida strategica su dove e come applicare l'IA nella tua organizzazione.",
    "forBusinesses.copilots.title": "Copiloti Personalizzati",
    "forBusinesses.copilots.desc": "Assistenti IA adattati ai tuoi workflow. Dal supporto clienti alle operazioni interne.",
    "forBusinesses.automation.title": "Automazione dei Processi",
    "forBusinesses.automation.desc": "Automatizza l'elaborazione di documenti e attività ripetitive.",
    "forBusinesses.enablement.title": "Formazione del Team",
    "forBusinesses.enablement.desc": "Forma il tuo team a lavorare efficacemente con gli strumenti IA.",
    // For Developers
    "forDevelopers.label": "Per gli Sviluppatori",
    "forDevelopers.title": "Costruire Soluzioni IA Insieme",
    "forDevelopers.subtitle": "Cerchiamo sempre sviluppatori qualificati per lavorare su progetti IA stimolanti. Che sia lavoro freelance o collaborazione continua, parliamone.",
    "forDevelopers.benefit1": "Progetti collaborativi con ingegneri IA esperti",
    "forDevelopers.benefit2": "Stack moderno: Python, TypeScript, cloud-native",
    "forDevelopers.benefit3": "Condizioni eque e comunicazione trasparente",
    "forDevelopers.benefit4": "Problemi interessanti in GenAI, LLM e MLOps",
    "forDevelopers.cta": "Contattaci",
    // Pricing
    "pricing.title": "Modelli di Impegno Flessibili",
    "pricing.subtitle": "Scegli il pacchetto adatto alle tue esigenze o discutiamo una soluzione personalizzata",
    "pricing.popular": "Più Popolare",
    "pricing.cta": "Inizia",
    "pricing.note": "Tutti i pacchetti includono consulenza iniziale e definizione del progetto gratuite.",
    "pricing.starter.name": "Starter",
    "pricing.starter.desc": "Perfetto per esplorare le possibilità dell'IA",
    "pricing.starter.price": "Da 5.000 €",
    "pricing.starter.period": "per progetto",
    "pricing.starter.feature1": "Valutazione di fattibilità IA",
    "pricing.starter.feature2": "Sviluppo proof of concept",
    "pricing.starter.feature3": "Fino a 4 settimane",
    "pricing.starter.feature4": "Documentazione tecnica",
    "pricing.starter.feature5": "1 ciclo di revisione",
    "pricing.growth.name": "Crescita",
    "pricing.growth.desc": "Per aziende pronte a scalare con l'IA",
    "pricing.growth.price": "Da 15.000 €",
    "pricing.growth.period": "per progetto",
    "pricing.growth.feature1": "Sviluppo MVP completo",
    "pricing.growth.feature2": "Integrazione modello IA personalizzato",
    "pricing.growth.feature3": "Fino a 8 settimane",
    "pricing.growth.feature4": "Formazione team inclusa",
    "pricing.growth.feature5": "3 cicli di revisione",
    "pricing.growth.feature6": "30 giorni di supporto post-lancio",
    "pricing.enterprise.name": "Enterprise",
    "pricing.enterprise.desc": "Trasformazione IA completa",
    "pricing.enterprise.price": "Personalizzato",
    "pricing.enterprise.period": "adattato alle tue esigenze",
    "pricing.enterprise.feature1": "Soluzione IA end-to-end",
    "pricing.enterprise.feature2": "Team di progetto dedicato",
    "pricing.enterprise.feature3": "Tempistiche flessibili",
    "pricing.enterprise.feature4": "Opzione deployment on-premise",
    "pricing.enterprise.feature5": "Revisioni illimitate",
    "pricing.enterprise.feature6": "Supporto e manutenzione continui",
    "pricing.enterprise.feature7": "Garanzie SLA",
    // Why Us
    "whyUs.label": "Perché Noi",
    "whyUs.title": "Costruiti Diversamente",
    "whyUs.subtitle": "Siamo un team piccolo e focalizzato che si vanta di consegnare lavoro eccezionale.",
    "whyUs.reason1.title": "Esecuzione dai Fondatori",
    "whyUs.reason1.desc": "Lavori direttamente con i fondatori. Nessun account manager, nessun livello.",
    "whyUs.reason2.title": "Veloce e Focalizzato",
    "whyUs.reason2.desc": "Ci muoviamo velocemente ma deliberatamente. Team piccolo, cicli di feedback stretti.",
    "whyUs.reason3.title": "Vera Competenza IA",
    "whyUs.reason3.desc": "Costruiamo con l'IA ogni giorno. Non consulenti—ingegneri che implementano in produzione.",
    // FAQ
    "faq.title": "Domande Frequenti",
    "faq.subtitle": "Hai domande? Abbiamo risposte.",
    "faq.q1": "Quali tipi di soluzioni IA offre xeda.ai?",
    "faq.a1": "Ci specializziamo in prodotti SaaS GenAI, MVP IA, soluzioni di automazione, consulenza di trasformazione IA e copiloti personalizzati.",
    "faq.q2": "Quanto tempo richiede un tipico progetto IA?",
    "faq.a2": "I tempi variano in base alla complessità. Un MVP IA può essere consegnato in 4-8 settimane, mentre progetti di trasformazione richiedono 3-6 mesi.",
    "faq.q3": "Ho bisogno di competenze tecniche per lavorare con xeda.ai?",
    "faq.a3": "Assolutamente no. Gestiamo tutti gli aspetti tecnici del progetto e lavoriamo con i tuoi stakeholder.",
    "faq.q4": "Come garantite la sicurezza e la privacy dei dati?",
    "faq.a4": "La sicurezza è fondamentale. Seguiamo la conformità GDPR e implementiamo la crittografia end-to-end.",
    "faq.q5": "Cosa distingue xeda.ai dalle altre agenzie IA?",
    "faq.a5": "Combiniamo la precisione dell'ingegneria tedesca con competenze IA all'avanguardia. Il nostro team costruisce sistemi di produzione.",
    "faq.q6": "Offrite supporto continuo dopo il completamento del progetto?",
    "faq.a6": "Sì, offriamo pacchetti flessibili di supporto e manutenzione. Molti clienti lavorano con noi in modo continuativo.",
    // Team
    "team.label": "Il Nostro Team",
    "team.title": "Incontra il Fondatore",
    "team.founder.role": "Fondatore",
    "team.subtitle": "Un piccolo team dedicato con profonda competenza in IA e passione per creare prodotti eccezionali.",
    "team.valuesTitle": "I Nostri Valori",
    "team.alex.role": "Co-fondatore & CEO",
    "team.alex.bio": "10+ anni di leadership tech. Ha costruito prodotti IA in aziende leader. Appassionato di soluzioni IA pratiche.",
    "team.maria.role": "Co-fondatrice & CTO",
    "team.maria.bio": "Ingegnera ML esperta in LLM e sistemi di produzione. Ex-ingegnera senior in laboratori di ricerca IA.",
    "team.value1.title": "Integrità",
    "team.value1.desc": "Siamo onesti su cosa l'IA può e non può fare.",
    "team.value2.title": "Innovazione",
    "team.value2.desc": "Restiamo all'avanguardia concentrandoci su applicazioni pratiche.",
    "team.value3.title": "Partnership",
    "team.value3.desc": "Lavoriamo al fianco del tuo team, non solo come fornitori esterni.",
    "team.value4.title": "Eccellenza",
    "team.value4.desc": "Ci impegniamo a consegnare lavoro di qualità che supera le aspettative.",
    // Contact
    "contact.title": "Parliamone",
    "contact.subtitle": "Che tu stia esplorando le possibilità dell'IA, pronto a iniziare un progetto, o interessato a collaborare—ci farebbe piacere sentirti.",
    "contact.name": "Nome",
    "contact.namePlaceholder": "Il tuo nome",
    "contact.email": "Email",
    "contact.emailPlaceholder": "tu@azienda.com",
    "contact.company": "Azienda",
    "contact.companyPlaceholder": "La tua azienda (opzionale)",
    "contact.message": "Messaggio",
    "contact.messagePlaceholder": "Raccontaci del tuo progetto o come possiamo aiutarti...",
    "contact.send": "Invia Messaggio",
    "contact.sending": "Invio in corso...",
    "contact.orEmail": "Oppure scrivici a",
    "contact.responseTime": "Di solito rispondiamo entro un giorno lavorativo.",
    "contact.success.title": "Messaggio inviato!",
    "contact.success.description": "Ti contatteremo entro un giorno lavorativo.",
    "contact.error.validation": "Errore di validazione",
    "contact.error.general": "Qualcosa è andato storto",
    "contact.error.tryAgain": "Per favore riprova o scrivici direttamente.",
    "contact.error.nameRequired": "Il nome è obbligatorio",
    "contact.error.nameTooLong": "Il nome deve avere meno di 100 caratteri",
    "contact.error.invalidEmail": "Indirizzo email non valido",
    "contact.error.emailTooLong": "L'email deve avere meno di 255 caratteri",
    "contact.error.companyTooLong": "L'azienda deve avere meno di 100 caratteri",
    "contact.error.messageRequired": "Il messaggio è obbligatorio",
    "contact.error.messageTooLong": "Il messaggio deve avere meno di 2000 caratteri",
    // Footer
    "footer.description": "Agenzia GenAI tedesca che costruisce soluzioni intelligenti per le aziende.",
    "footer.careers": "Carriere — cerchiamo sviluppatori →",
    // Blog
    "blog.label": "Approfondimenti",
    "blog.title": "Insights e Novità IA",
    "blog.subtitle": "Resta informato sulle ultime tendenze, best practice e insights dai nostri esperti IA.",
    "blog.readMore": "Leggi di più",
    "blog.viewAll": "Vedi tutti gli articoli",
    // Blog Page
    "blogPage.backHome": "Torna alla Home",
    "blogPage.searchPlaceholder": "Cerca articoli...",
    "blogPage.allCategories": "Tutti",
    "blogPage.noResults": "Nessun articolo trovato.",
    "blogPage.post4.title": "Costruire un'infrastruttura IA scalabile: Lezioni dalla produzione",
    "blogPage.post4.excerpt": "Insights chiave dal deployment di sistemi IA su larga scala, inclusi pattern architetturali e ottimizzazione dei costi.",
    "blogPage.post5.title": "RAG vs Fine-tuning: Scegliere l'approccio giusto per il tuo LLM",
    "blogPage.post5.excerpt": "Un'analisi tecnica approfondita di RAG e fine-tuning con guida pratica.",
    "blogPage.post6.title": "Regolamentazione IA in Europa: Cosa riserva il 2025 alle aziende",
    "blogPage.post6.excerpt": "Una panoramica delle prossime normative IA nell'UE e come le aziende possono prepararsi.",
    // Blog Post Page
    "blogPost.notFound": "Articolo non trovato",
    "blogPost.notFoundDesc": "L'articolo che stai cercando non esiste o è stato spostato.",
    "blogPost.backToBlog": "Torna al Blog",
    "blogPost.readTime": "di lettura",
    "blogPost.minRemaining": "min rimasti",
    "blogPost.relatedPosts": "Articoli correlati",
    "blogPost.toc.introduction": "Introduzione",
    "blogPost.toc.content": "Articolo",
    "blogPost.toc.author": "L'autore",
    "blogPost.toc.newsletter": "Newsletter",
    "blogPost.toc.related": "Articoli simili",
    "blogPost.share": "Condividi",
    "blogPost.ctaTitle": "Pronto a trasformare la tua azienda con l'IA?",
    "blogPost.ctaDesc": "Lascia che ti aiutiamo a implementare soluzioni IA che portano risultati reali.",
    "blogPost.ctaButton": "Contattaci",
    "blogPost.newsletter.title": "Non perdere nessun aggiornamento",
    "blogPost.newsletter.desc": "Iscriviti alla nostra newsletter e ricevi gli ultimi insight IA direttamente nella tua casella di posta.",
    "blogPost.newsletter.button": "Iscriviti",
    "blogPost.author.alexBio": "Alex guida xeda.ai con l'obiettivo di colmare il divario tra la ricerca IA all'avanguardia e le applicazioni aziendali pratiche. Con oltre 10 anni di esperienza nella leadership tecnologica, è appassionato nell'aiutare le aziende a sbloccare valore attraverso l'automazione intelligente.",
    "blogPost.author.mariaBio": "Maria porta una profonda competenza tecnica in machine learning e architettura software a xeda.ai. È specializzata nella progettazione di sistemi IA scalabili e ha guidato implementazioni di successo per aziende in tutta Europa.",
    "blogPost.post4.content": "Scalare sistemi IA dal proof-of-concept alla produzione è una sfida comune.\n\nL'architettura conta dal primo giorno. Progetta per la scalabilità.\n\nIl monitoraggio non è opzionale. I sistemi IA possono fallire silenziosamente.\n\nVersiona tutto. Modelli, dati, configurazioni.",
    "blogPost.post5.content": "RAG e fine-tuning sono due approcci fondamentali per personalizzare gli LLM.\n\nRAG recupera documenti rilevanti e li fornisce come contesto. Ideale quando la tua knowledge base cambia frequentemente.\n\nIl fine-tuning modifica i pesi del modello. Eccellente per output consistente.\n\nNella pratica, molti combinano entrambi gli approcci.",
    "blogPost.post6.content": "Il AI Act dell'UE è la regolamentazione IA più completa a livello globale.\n\nLa normativa introduce un sistema di classificazione basato sul rischio.\n\nLe tempistiche sono scaglionate. Alcune disposizioni sono già in vigore.\n\nI requisiti di documentazione sono sostanziali.\n\nLa nostra raccomandazione: esegui un inventario IA ora.",
    "footer.legal": "Legale",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Termini di Servizio",
    "footer.impressum": "Note Legali",
    "footer.rights": "Con sede in Germania.",
    "footer.newsletter.title": "Resta Aggiornato",
    "footer.newsletter.description": "Iscriviti alla nostra newsletter per insight IA e aggiornamenti.",
    "footer.newsletter.placeholder": "tua@email.com",
    "footer.newsletter.invalidEmail": "Email non valida",
    "footer.newsletter.enterValid": "Per favore inserisci un indirizzo email valido.",
    "footer.newsletter.alreadySubscribed": "Già iscritto",
    "footer.newsletter.alreadyOnList": "Questa email è già nella nostra lista.",
    "footer.newsletter.subscribed": "Iscritto!",
    "footer.newsletter.thankYou": "Grazie per esserti iscritto alla nostra newsletter.",
    "footer.newsletter.error": "Qualcosa è andato storto",
    "footer.newsletter.tryLater": "Per favore riprova più tardi.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const languageLabels: Record<SiteLanguage, { name: string; flag: string }> = {
  en: { name: "English", flag: "🇬🇧" },
  de: { name: "Deutsch", flag: "🇩🇪" },
  fr: { name: "Français", flag: "🇫🇷" },
  es: { name: "Español", flag: "🇪🇸" },
  it: { name: "Italiano", flag: "🇮🇹" },
};

const supportedLanguages: SiteLanguage[] = ["en", "de", "fr", "es", "it"];

const detectBrowserLanguage = (): SiteLanguage => {
  const browserLang = navigator.language.split("-")[0].toLowerCase();
  if (supportedLanguages.includes(browserLang as SiteLanguage)) {
    return browserLang as SiteLanguage;
  }
  return "en";
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<SiteLanguage>(() => {
    const saved = localStorage.getItem("site_language");
    if (saved && supportedLanguages.includes(saved as SiteLanguage)) {
      return saved as SiteLanguage;
    }
    // Auto-detect from browser if no saved preference
    return detectBrowserLanguage();
  });

  useEffect(() => {
    localStorage.setItem("site_language", language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: SiteLanguage) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
